package com.jetbrains.youtrackdb.internal.annotations.gremlin.dsl;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.zip.CRC32;
import org.jetbrains.annotations.Nullable;

/**
 * Helper for DSL source digest (CRC32) used to decide whether to skip regeneration.
 * Extracted for unit testing.
 */
public final class GremlinDslDigestHelper {

  /** Comment line prefix written into generated files; stored digest follows. */
  public static final String DSL_SOURCE_DIGEST_PREFIX =
      "Generated by GremlinDslProcessor; DSL source digest: ";

  private GremlinDslDigestHelper() {
  }

  /** CRC32 of file content (hex string). Returns empty string if the file cannot be read. */
  public static String computeSourceDigest(final Path sourcePath) {
    try {
      var bytes = Files.readAllBytes(sourcePath);
      var crc = new CRC32();
      crc.update(bytes);
      return Long.toHexString(crc.getValue());
    } catch (IOException e) {
      return "";
    }
  }

  /**
   * Reads the stored DSL source digest from a generated file's comment line.
   * Returns null if the file does not exist or the comment line is missing/invalid.
   */
  @Nullable
  public static String getStoredDigestFromGeneratedFile(final Path generatedPath) {
    if (!Files.isRegularFile(generatedPath)) {
      return null;
    }
    try {
      var lines = Files.readAllLines(generatedPath);
      for (var line : lines) {
        if (line.contains(DSL_SOURCE_DIGEST_PREFIX)) {
          var start = line.indexOf(DSL_SOURCE_DIGEST_PREFIX) + DSL_SOURCE_DIGEST_PREFIX.length();
          return line.substring(start).trim();
        }
      }
    } catch (IOException ignored) {
      return null;
    }
    return null;
  }
}
