/* Generated By:JJTree: Do not edit this line. SQLContainsTextCondition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrackdb.internal.core.sql.parser;

import com.jetbrains.youtrackdb.internal.core.command.CommandContext;
import com.jetbrains.youtrackdb.internal.core.db.DatabaseSessionEmbedded;
import com.jetbrains.youtrackdb.internal.core.db.record.record.Identifiable;
import com.jetbrains.youtrackdb.internal.core.metadata.schema.schema.Collate;
import com.jetbrains.youtrackdb.internal.core.query.Result;
import com.jetbrains.youtrackdb.internal.core.sql.executor.IndexSearchInfo;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

public class SQLContainsTextCondition extends SQLBooleanExpression {

  protected SQLExpression left;
  protected SQLExpression right;

  private final TextCollationResolver collate = new TextCollationResolver();

  /**
   * When {@code true}, a present non-{@code String} left operand throws {@link
   * com.jetbrains.youtrackdb.internal.core.exception.NonStringTextOperandException} instead of
   * yielding {@code false}, mirroring native TinkerPop {@code Text.containing} (String-only). It is
   * set only when the node is built programmatically by the Gremlin adapter; parser-built (SQL/GQL)
   * nodes leave it {@code false}, so their lenient behavior is unchanged. Strict applies only to the
   * plain-property path; the {@code any()} / {@code all()} function paths are never built by the
   * Gremlin adapter and stay lenient. The flag is value-carrying: it participates in {@link #copy},
   * {@link #equals} / {@link #hashCode}, and {@link #splitForAggregation}, and is reflected in {@link
   * #toGenericStatement} so a strict node and a lenient node on the same operands do not collide on
   * their plan-cache fingerprint.
   */
  protected boolean strict = false;

  public SQLContainsTextCondition(int id) {
    super(id);
  }

  public SQLContainsTextCondition(YouTrackDBSql p, int id) {
    super(p, id);
  }

  @Override
  public boolean evaluate(Identifiable currentRecord, CommandContext ctx) {
    // Type-check the left operand before any collate transform: strict throws on a present
    // non-String, lenient (and null/absent) yields false.
    var leftValue =
        TextCollationResolver.requireStringOperand(left.execute(currentRecord, ctx), strict,
            "CONTAINSTEXT");
    if (leftValue == null) {
      return false;
    }
    if (!(right.execute(currentRecord, ctx) instanceof String rightValue)) {
      return false;
    }
    return containsCollated(leftValue, rightValue, collate.resolve(left, right, currentRecord, ctx));
  }

  @Override
  public boolean evaluate(Result currentRecord, CommandContext ctx) {
    if (left.isFunctionAny()) {
      return evaluateAny(currentRecord, ctx);
    }

    if (left.isFunctionAll()) {
      return evaluateAllFunction(currentRecord, ctx);
    }
    var leftValue =
        TextCollationResolver.requireStringOperand(left.execute(currentRecord, ctx), strict,
            "CONTAINSTEXT");
    if (leftValue == null) {
      return false;
    }
    if (!(right.execute(currentRecord, ctx) instanceof String rightValue)) {
      return false;
    }
    return containsCollated(leftValue, rightValue, collate.resolve(left, right, currentRecord, ctx));
  }

  private boolean evaluateAny(Result currentRecord, CommandContext ctx) {
    if (!(right.execute(currentRecord, ctx) instanceof String rightValue)) {
      return false;
    }

    for (var s : currentRecord.getPropertyNames()) {
      if (!(currentRecord.getProperty(s) instanceof String leftValue)) {
        continue;
      }

      // any() spans every property, so each property carries its own declared collation.
      if (containsCollated(
          leftValue, rightValue, TextCollationResolver.forProperty(currentRecord, s, ctx))) {
        return true;
      }
    }
    return false;
  }

  private boolean evaluateAllFunction(Result currentRecord, CommandContext ctx) {
    if (!(right.execute(currentRecord, ctx) instanceof String rightValue)) {
      return false;
    }

    for (var s : currentRecord.getPropertyNames()) {
      if (!(currentRecord.getProperty(s) instanceof String leftValue)) {
        return false;
      }

      if (!containsCollated(
          leftValue, rightValue, TextCollationResolver.forProperty(currentRecord, s, ctx))) {
        return false;
      }
    }
    return true;
  }

  /** Applies {@code collate} (if any) to both operands, then tests substring containment. */
  private static boolean containsCollated(String value, String substring,
      @Nullable Collate collate) {
    return TextCollationResolver.apply(value, collate)
            .indexOf(TextCollationResolver.apply(substring, collate))
        > -1;
  }

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {
    left.toString(params, builder);
    builder.append(" CONTAINSTEXT ");
    right.toString(params, builder);
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {
    left.toGenericStatement(builder);
    // Distinct token in strict mode so a strict node and a lenient node on the same operands produce
    // different plan-cache fingerprints. Parser-built nodes are lenient, so their token is unchanged.
    builder.append(strict ? " CONTAINSTEXT(strict) " : " CONTAINSTEXT ");
    right.toGenericStatement(builder);
  }

  @Override
  public boolean supportsBasicCalculation() {
    return true;
  }

  @Override
  protected int getNumberOfExternalCalculations() {
    var total = 0;
    if (!left.supportsBasicCalculation()) {
      total++;
    }
    if (!right.supportsBasicCalculation()) {
      total++;
    }
    return total;
  }

  @Override
  protected List<Object> getExternalCalculationConditions() {
    List<Object> result = new ArrayList<Object>();
    if (!left.supportsBasicCalculation()) {
      result.add(left);
    }
    if (!right.supportsBasicCalculation()) {
      result.add(right);
    }
    return result;
  }

  @Override
  public boolean needsAliases(Set<String> aliases) {
    if (!left.needsAliases(aliases)) {
      return true;
    }
    return !right.needsAliases(aliases);
  }

  @Override
  public SQLContainsTextCondition copy() {
    var result = new SQLContainsTextCondition(-1);
    result.left = left.copy();
    result.right = right.copy();
    result.strict = strict;
    return result;
  }

  @Override
  public void extractSubQueries(SubQueryCollector collector) {
    left.extractSubQueries(collector);
    right.extractSubQueries(collector);
  }

  @Override
  public boolean refersToParent() {
    return left.refersToParent() || right.refersToParent();
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    var that = (SQLContainsTextCondition) o;

    if (!Objects.equals(left, that.left)) {
      return false;
    }
    if (!Objects.equals(right, that.right)) {
      return false;
    }
    return strict == that.strict;
  }

  @Override
  public int hashCode() {
    var result = left != null ? left.hashCode() : 0;
    result = 31 * result + (right != null ? right.hashCode() : 0);
    result = 31 * result + (strict ? 1 : 0);
    return result;
  }

  @Nullable
  @Override
  public List<String> getMatchPatternInvolvedAliases() {
    var leftX = left == null ? null : left.getMatchPatternInvolvedAliases();
    var rightX = right == null ? null : right.getMatchPatternInvolvedAliases();

    List<String> result = new ArrayList<String>();
    if (leftX != null) {
      result.addAll(leftX);
    }
    if (rightX != null) {
      result.addAll(rightX);
    }

    return result.size() == 0 ? null : result;
  }

  @Override
  public boolean isCacheable(DatabaseSessionEmbedded session) {
    if (left != null && !left.isCacheable(session)) {
      return false;
    }
    return right == null || right.isCacheable(session);
  }

  @Override
  public boolean isIndexAware(IndexSearchInfo info, CommandContext ctx) {
    return false;
  }

  @Override
  public boolean isRangeExpression() {
    return false;
  }

  @Nullable
  @Override
  public String getRelatedIndexPropertyName() {
    return null;
  }

  @Nullable
  @Override
  public SQLBooleanExpression mergeUsingAnd(SQLBooleanExpression other,
      @Nonnull CommandContext ctx) {
    return null;
  }

  public void setLeft(SQLExpression left) {
    this.left = left;
  }

  public void setRight(SQLExpression right) {
    this.right = right;
  }

  public SQLExpression getLeft() {
    return left;
  }

  public SQLExpression getRight() {
    return right;
  }

  public void setStrict(boolean strict) {
    this.strict = strict;
  }

  public boolean isStrict() {
    return strict;
  }

  @Override
  public boolean isFullTextIndexAware(String indexField) {
    if (left.isBaseIdentifier()) {
      var fieldName = left.getDefaultAlias().getStringValue();
      return indexField.equals(fieldName);
    }
    return false;
  }

  @Override
  public SQLExpression resolveKeyFrom(SQLBinaryCondition additional) {
    if (right != null) {
      return right;
    } else {
      throw new UnsupportedOperationException("Cannot execute index query with " + this);
    }
  }

  @Override
  public SQLExpression resolveKeyTo(SQLBinaryCondition additional) {
    return right;
  }

  @Override
  public boolean varMightBeInUse(String varName) {
    return left != null && left.varMightBeInUse(varName) ||
        right != null && right.varMightBeInUse(varName);
  }

  @Override
  public boolean isAggregate(DatabaseSessionEmbedded session) {
    return left != null && left.isAggregate(session)
        || right != null && right.isAggregate(session);
  }

  @Override
  public SQLBooleanExpression splitForAggregation(
      AggregateProjectionSplit aggregateProj, CommandContext ctx) {
    if (!isAggregate(ctx.getDatabaseSession())) {
      return this;
    }
    var result = new SQLContainsTextCondition(-1);
    result.left = left == null ? null : left.splitForAggregation(aggregateProj, ctx);
    result.right = right == null ? null : right.splitForAggregation(aggregateProj, ctx);
    result.strict = strict;
    return result;
  }
}
/* JavaCC - OriginalChecksum=b588492ba2cbd0f932055f1f64bbbecd (do not edit this line) */
