/* Generated By:JJTree: Do not edit this line. SQLMatchesCondition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrackdb.internal.core.sql.parser;

import com.jetbrains.youtrackdb.internal.core.command.CommandContext;
import com.jetbrains.youtrackdb.internal.core.db.DatabaseSessionEmbedded;
import com.jetbrains.youtrackdb.internal.core.db.record.record.Identifiable;
import com.jetbrains.youtrackdb.internal.core.query.Result;
import com.jetbrains.youtrackdb.internal.core.sql.executor.IndexSearchInfo;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

public class SQLMatchesCondition extends SQLBooleanExpression {

  protected SQLExpression expression;

  protected String right;
  protected SQLExpression rightExpression;
  protected SQLInputParameter rightParam;

  /**
   * When {@code true}, the pattern is tested with {@link java.util.regex.Matcher#find()}
   * (an unanchored match anywhere in the value) instead of {@link java.util.regex.Matcher#matches()}
   * (a full-value match). Parsed SQL {@code MATCHES} is always full-match, so this flag stays
   * {@code false} for parsed conditions; it is set only when the node is built programmatically to
   * back the Gremlin {@code Text.regex} predicate, whose semantics are find-anywhere. The flag is a
   * value-carrying field: it participates in {@link #copy}, {@link #equals} / {@link #hashCode}, and
   * {@link #splitForAggregation}, and it is reflected in {@link #toGenericStatement} so a find-mode
   * node and a full-match node on the same expression and pattern do not collide on their plan-cache
   * fingerprint.
   */
  protected boolean findMode = false;

  /**
   * When {@code true}, a present non-{@code String} value throws {@link
   * com.jetbrains.youtrackdb.internal.core.exception.NonStringTextOperandException} instead of
   * yielding {@code false}, mirroring native TinkerPop {@code Text.regex} (String-only). It is set
   * only when the node is built programmatically by the Gremlin adapter; parser-built (SQL/GQL)
   * nodes leave it {@code false}, so their lenient behavior is unchanged. A present-{@code null}
   * value stays return-false (it is never thrown on) — native regex NPEs there, but reproducing that
   * NPE is an accepted non-goal. The flag is value-carrying: it participates in {@link #copy}, {@link
   * #equals} / {@link #hashCode}, and {@link #splitForAggregation}, and is reflected in {@link
   * #toGenericStatement} so a strict node and a lenient node with the same expression, pattern, and
   * find-mode do not collide on their plan-cache fingerprint.
   */
  protected boolean strict = false;

  public SQLMatchesCondition(int id) {
    super(id);
  }

  public SQLMatchesCondition(YouTrackDBSql p, int id) {
    super(p, id);
  }

  @Override
  public boolean evaluate(Identifiable currentRecord, CommandContext ctx) {
    var regex = right;
    if (regex != null) {
      regex = regex.substring(1, regex.length() - 1);
    } else if (rightExpression != null) {
      var val = rightExpression.execute(currentRecord, ctx);
      if (val instanceof String) {
        regex = (String) val;
      } else {
        return false;
      }
    } else {
      var paramVal = rightParam.getValue(ctx.getInputParameters());
      if (paramVal instanceof String) {
        regex = (String) paramVal;
      } else {
        return false;
      }
    }
    var value = expression.execute(currentRecord, ctx);

    // Strict Gremlin parity: throw on a present non-String value before matching. The helper never
    // throws on null, so a present-null value falls through to matches() below, which returns false
    // for it (native regex would NPE on null — reproducing that is an accepted non-goal).
    TextCollationResolver.requireStringOperand(value, strict, "MATCHES");
    return matches(value, regex, findMode, ctx);
  }

  private static boolean matches(Object value, String regex, boolean findMode, CommandContext ctx) {
    final var key = "MATCHES_" + regex.hashCode();
    var p = (java.util.regex.Pattern) ctx.getVariable(key);
    if (p == null) {
      p = java.util.regex.Pattern.compile(regex);
      ctx.setVariable(key, p);
    }

    if (value instanceof CharSequence) {
      var matcher = p.matcher((CharSequence) value);
      // find() matches a substring anywhere (Gremlin Text.regex); matches() requires the whole
      // value to match (SQL MATCHES). The compiled Pattern is identical either way, so the cache
      // key above is shared across both modes.
      return findMode ? matcher.find() : matcher.matches();
    } else {
      return false;
    }
  }

  @Override
  public boolean evaluate(Result currentRecord, CommandContext ctx) {
    var regex = right;
    if (regex != null) {
      regex = regex.substring(1, regex.length() - 1);
    } else if (rightExpression != null) {
      var val = rightExpression.execute(currentRecord, ctx);
      if (val instanceof String) {
        regex = (String) val;
      } else {
        return false;
      }
    } else {
      var paramVal = rightParam.getValue(ctx.getInputParameters());
      if (paramVal instanceof String) {
        regex = (String) paramVal;
      } else {
        return false;
      }
    }
    var value = expression.execute(currentRecord, ctx);

    // See the Identifiable overload: strict throws on a present non-String; present-null returns
    // false via matches() below.
    TextCollationResolver.requireStringOperand(value, strict, "MATCHES");
    return matches(value, regex, findMode, ctx);
  }

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {
    expression.toString(params, builder);
    builder.append(" MATCHES ");
    if (right != null) {
      builder.append(right);
    } else if (rightExpression != null) {
      rightExpression.toString(params, builder);
    } else {
      rightParam.toString(params, builder);
    }
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {
    expression.toGenericStatement(builder);
    // Distinct operator token per mode so a find-mode node and a full-match node on the same
    // expression and pattern produce different fingerprints (the plan-cache key is the generic
    // statement). Parsed SQL is always full-match, so its fingerprint is unchanged.
    // Distinct token per mode combination (find and/or strict) so nodes that differ only in a mode
    // flag get different fingerprints. Parsed SQL is lenient full-match, so " MATCHES " is unchanged.
    builder.append(" MATCHES");
    if (findMode) {
      builder.append("(find)");
    }
    if (strict) {
      builder.append("(strict)");
    }
    builder.append(' ');
    if (right != null) {
      builder.append(PARAMETER_PLACEHOLDER);
    } else if (rightExpression != null) {
      rightExpression.toGenericStatement(builder);
    } else {
      rightParam.toGenericStatement(builder);
    }
  }

  @Override
  public boolean supportsBasicCalculation() {
    if (!expression.supportsBasicCalculation()) {
      return false;
    }
    return rightExpression == null || rightExpression.supportsBasicCalculation();
  }

  @Override
  protected int getNumberOfExternalCalculations() {
    var result = 0;
    if (expression != null && !expression.supportsBasicCalculation()) {
      result++;
    }
    if (rightExpression != null && !rightExpression.supportsBasicCalculation()) {
      result++;
    }
    return result;
  }

  @Override
  protected List<Object> getExternalCalculationConditions() {
    List<Object> result = new ArrayList<>();
    if (expression != null && !expression.supportsBasicCalculation()) {
      result.add(expression);
    }
    if (rightExpression != null && !rightExpression.supportsBasicCalculation()) {
      result.add(rightExpression);
    }
    return result;
  }

  @Override
  public boolean needsAliases(Set<String> aliases) {
    if (expression.needsAliases(aliases)) {
      return true;
    }
    return rightExpression.needsAliases(aliases);
  }

  @Override
  public SQLMatchesCondition copy() {
    var result = new SQLMatchesCondition(-1);
    result.expression = expression == null ? null : expression.copy();
    result.right = right;
    result.rightParam = rightParam == null ? null : rightParam.copy();
    result.rightExpression = rightExpression == null ? null : rightExpression.copy();
    result.findMode = findMode;
    result.strict = strict;
    return result;
  }

  public void setExpression(SQLExpression expression) {
    this.expression = expression;
  }

  public void setRightExpression(SQLExpression rightExpression) {
    this.rightExpression = rightExpression;
  }

  public void setFindMode(boolean findMode) {
    this.findMode = findMode;
  }

  public boolean isFindMode() {
    return findMode;
  }

  public void setStrict(boolean strict) {
    this.strict = strict;
  }

  public boolean isStrict() {
    return strict;
  }

  @Override
  public void extractSubQueries(SubQueryCollector collector) {
    expression.extractSubQueries(collector);
    if (rightExpression != null) {
      rightExpression.extractSubQueries(collector);
    }
  }

  @Override
  public boolean refersToParent() {
    if (expression != null && expression.refersToParent()) {
      return true;
    }
    return rightExpression != null && rightExpression.refersToParent();
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    var that = (SQLMatchesCondition) o;

    if (!Objects.equals(expression, that.expression)) {
      return false;
    }
    if (!Objects.equals(right, that.right)) {
      return false;
    }
    if (!Objects.equals(rightExpression, that.rightExpression)) {
      return false;
    }
    if (!Objects.equals(rightParam, that.rightParam)) {
      return false;
    }
    if (findMode != that.findMode) {
      return false;
    }
    return strict == that.strict;
  }

  @Override
  public int hashCode() {
    var result = expression != null ? expression.hashCode() : 0;
    result = 31 * result + (right != null ? right.hashCode() : 0);
    result = 31 * result + (rightExpression != null ? rightExpression.hashCode() : 0);
    result = 31 * result + (rightParam != null ? rightParam.hashCode() : 0);
    result = 31 * result + (findMode ? 1 : 0);
    result = 31 * result + (strict ? 1 : 0);
    return result;
  }

  @Override
  public List<String> getMatchPatternInvolvedAliases() {
    List<String> result = new ArrayList<>(expression.getMatchPatternInvolvedAliases());
    if (rightExpression != null) {
      result.addAll(rightExpression.getMatchPatternInvolvedAliases());
    }
    return result;
  }

  @Override
  public boolean isCacheable(DatabaseSessionEmbedded session) {
    if (!expression.isCacheable(session)) {
      return false;
    }
    return rightExpression == null || rightExpression.isCacheable(session);
  }

  @Override
  public boolean isIndexAware(IndexSearchInfo info, CommandContext ctx) {
    return false;
  }

  @Override
  public boolean isRangeExpression() {
    return false;
  }

  @Nullable
  @Override
  public String getRelatedIndexPropertyName() {
    return null;
  }

  @Nullable
  @Override
  public SQLBooleanExpression mergeUsingAnd(SQLBooleanExpression other,
      @Nonnull CommandContext ctx) {
    return null;
  }

  @Override
  public boolean varMightBeInUse(String varName) {
    return expression != null && expression.varMightBeInUse(varName) ||
        rightExpression != null && rightExpression.varMightBeInUse(varName);
  }

  @Override
  public boolean isAggregate(DatabaseSessionEmbedded session) {
    return expression != null && expression.isAggregate(session)
        || rightExpression != null && rightExpression.isAggregate(session);
  }

  @Override
  public SQLBooleanExpression splitForAggregation(
      AggregateProjectionSplit aggregateProj, CommandContext ctx) {
    if (!isAggregate(ctx.getDatabaseSession())) {
      return this;
    }
    var result = new SQLMatchesCondition(-1);
    result.expression = expression == null ? null
        : expression.splitForAggregation(aggregateProj, ctx);
    result.right = right;
    result.rightParam = rightParam == null ? null : rightParam.copy();
    result.rightExpression = rightExpression == null ? null
        : rightExpression.splitForAggregation(aggregateProj, ctx);
    result.findMode = findMode;
    result.strict = strict;
    return result;
  }
}
/* JavaCC - OriginalChecksum=68712f476e2e633c2bbfc34cb6c39356 (do not edit this line) */
