/* Generated By:JJTree: Do not edit this line. SQLOptimizeDatabaseStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrackdb.internal.core.sql.parser;

import com.jetbrains.youtrackdb.internal.common.log.LogManager;
import com.jetbrains.youtrackdb.internal.core.command.CommandContext;
import com.jetbrains.youtrackdb.internal.core.db.DatabaseSessionEmbedded;
import com.jetbrains.youtrackdb.internal.core.db.record.record.RID;
import com.jetbrains.youtrackdb.internal.core.db.record.ridbag.LinkBag;
import com.jetbrains.youtrackdb.internal.core.record.impl.EntityImpl;
import com.jetbrains.youtrackdb.internal.core.sql.executor.ResultInternal;
import com.jetbrains.youtrackdb.internal.core.sql.executor.resultset.ExecutionStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;

public class SQLOptimizeDatabaseStatement extends SQLSimpleExecStatement {

  protected List<SQLCommandLineOption> options = new ArrayList<SQLCommandLineOption>();

  public SQLOptimizeDatabaseStatement(int id) {
    super(id);
  }

  public SQLOptimizeDatabaseStatement(YouTrackDBSql p, int id) {
    super(p, id);
  }

  public void addOption(SQLCommandLineOption option) {
    this.options.add(option);
  }

  @Override
  public ExecutionStream executeSimple(CommandContext ctx) {
    var db = ctx.getDatabaseSession();
    var result = new ResultInternal(db);
    result.setProperty("operation", "optimize databae");

    if (isOptimizeEdges()) {
      var edges = optimizeEdges(db);
      result.setProperty("optimizeEdges", edges);
    }

    return ExecutionStream.singleton(result);
  }

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {
    builder.append("OPTIMIZE DATABASE");
    for (var option : options) {
      builder.append(" ");
      option.toString(params, builder);
    }
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {
    builder.append("OPTIMIZE DATABASE");
    for (var option : options) {
      builder.append(" ");
      option.toGenericStatement(builder);
    }
  }

  @Override
  public SQLOptimizeDatabaseStatement copy() {
    var result = new SQLOptimizeDatabaseStatement(-1);
    result.options =
        options == null
            ? null
            : options.stream().map(SQLCommandLineOption::copy).collect(Collectors.toList());
    return result;
  }

  private String optimizeEdges(DatabaseSessionEmbedded db) {
    long transformed = 0;
    final var totalEdges = db.countClass("E");
    long browsedEdges = 0;
    long lastLapBrowsed = 0;
    var lastLapTime = System.currentTimeMillis();

    try (var iter = db.browseClass("E")) {
      while (iter.hasNext()) {
        var entity = iter.next();
        if (Thread.currentThread().isInterrupted()) {
          break;
        }

        browsedEdges++;

        if (entity != null) {
          if (entity.getPropertiesCount() == 2) {
            final RID edgeIdentity = entity.getIdentity();

            final EntityImpl outV = entity.getPropertyInternal("out");
            final EntityImpl inV = entity.getPropertyInternal("in");

            // OUTGOING
            final var outField = outV.getPropertyInternal("out_" + entity.getSchemaClassName());
            if (outField instanceof LinkBag) {
              final var it = ((LinkBag) outField).iterator();
              while (it.hasNext()) {
                var v = it.next();
                if (edgeIdentity.equals(v)) {
                  // REPLACE EDGE RID WITH IN-VERTEX RID
                  it.remove();
                  ((LinkBag) outField).add(inV.getIdentity());
                  break;
                }
              }
            }

            // INCOMING
            final var inField = inV.getPropertyInternal("in_" + entity.getSchemaClassName());
            if (outField instanceof LinkBag) {
              final var it = ((LinkBag) inField).iterator();
              while (it.hasNext()) {
                var v = it.next();
                if (edgeIdentity.equals(v)) {
                  // REPLACE EDGE RID WITH IN-VERTEX RID
                  it.remove();
                  ((LinkBag) inField).add(outV.getIdentity());
                  break;
                }
              }
            }

            entity.delete();

            final var now = System.currentTimeMillis();

            if (verbose() && (now - lastLapTime > 2000)) {
              final var elapsed = now - lastLapTime;

              LogManager.instance()
                  .info(
                      this,
                      "Browsed %,d of %,d edges, transformed %,d so far (%,d edges/sec)",
                      browsedEdges,
                      totalEdges,
                      transformed,
                      (((browsedEdges - lastLapBrowsed) * 1000 / elapsed)));

              lastLapTime = System.currentTimeMillis();
              lastLapBrowsed = browsedEdges;
            }
          }
        }
      }
    }

    return "Transformed " + transformed + " regular edges in lightweight edges";
  }

  private boolean isOptimizeEdges() {
    for (var option : options) {
      if (option.name.getStringValue().equalsIgnoreCase("LWEDGES")) {
        return true;
      }
    }
    return false;
  }

  private boolean verbose() {
    for (var option : options) {
      if (option.name.getStringValue().equalsIgnoreCase("NOVERBOSE")) {
        return false;
      }
    }
    return true;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    var that = (SQLOptimizeDatabaseStatement) o;

    return Objects.equals(options, that.options);
  }

  @Override
  public int hashCode() {
    return options != null ? options.hashCode() : 0;
  }
}
/* JavaCC - OriginalChecksum=b85d66f84bbae92224565361df9d0c91 (do not edit this line) */
