/* Generated By:JJTree: Do not edit this line. SQLWhereClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrackdb.internal.core.sql.parser;

import com.jetbrains.youtrackdb.internal.common.util.RawPair;
import com.jetbrains.youtrackdb.internal.core.command.CommandContext;
import com.jetbrains.youtrackdb.internal.core.db.DatabaseSessionEmbedded;
import com.jetbrains.youtrackdb.internal.core.db.record.record.Identifiable;
import com.jetbrains.youtrackdb.internal.core.db.record.record.RID;
import com.jetbrains.youtrackdb.internal.core.index.CompositeIndexDefinition;
import com.jetbrains.youtrackdb.internal.core.index.CompositeKey;
import com.jetbrains.youtrackdb.internal.core.index.Index;
import com.jetbrains.youtrackdb.internal.core.index.PropertyIndexDefinition;
import com.jetbrains.youtrackdb.internal.core.index.engine.EquiDepthHistogram;
import com.jetbrains.youtrackdb.internal.core.index.engine.IndexStatistics;
import com.jetbrains.youtrackdb.internal.core.index.engine.SelectivityEstimator;
import com.jetbrains.youtrackdb.internal.core.metadata.schema.PropertyTypeInternal;
import com.jetbrains.youtrackdb.internal.core.metadata.schema.SchemaClassInternal;
import com.jetbrains.youtrackdb.internal.core.query.Result;
import com.jetbrains.youtrackdb.internal.core.sql.executor.ResultInternal;
import com.jetbrains.youtrackdb.internal.core.sql.executor.metadata.IndexCandidate;
import com.jetbrains.youtrackdb.internal.core.sql.executor.metadata.IndexFinder;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.Spliterator;
import java.util.stream.Collectors;
import javax.annotation.Nullable;

public class SQLWhereClause extends SimpleNode {

  protected SQLBooleanExpression baseExpression;

  private List<SQLAndBlock> flattened;

  public SQLWhereClause(int id) {
    super(id);
  }

  public SQLWhereClause(YouTrackDBSql p, int id) {
    super(p, id);
  }

  public boolean matchesFilters(Identifiable currentRecord, CommandContext ctx) {
    if (baseExpression == null) {
      return true;
    }
    return baseExpression.evaluate(currentRecord, ctx);
  }

  public boolean matchesFilters(Result currentRecord, CommandContext ctx) {
    if (baseExpression == null) {
      return true;
    }
    return baseExpression.evaluate(currentRecord, ctx);
  }

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {
    if (baseExpression == null) {
      return;
    }
    baseExpression.toString(params, builder);
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {
    if (baseExpression == null) {
      return;
    }
    baseExpression.toGenericStatement(builder);
  }

  /**
   * estimates how many items of this class will be returned applying this filter
   *
   * @return an estimation of the number of records of this class returned applying this filter, 0
   * if and only if sure that no records are returned
   */
  public long estimate(SchemaClassInternal schemaClass, long threshold, CommandContext ctx) {
    var session = ctx.getDatabaseSession();
    var classCount = schemaClass.approximateCount(session);
    if (classCount <= 0) {
      return 0;
    }

    // Upper-bound estimate: count/2 heuristic when no histogram is available.
    var count = classCount > 1 ? classCount / 2 : classCount;
    if (count < threshold) {
      return count;
    }

    var indexesCount = 0L;
    var flattenedConditions = flatten(ctx, schemaClass);
    var indexes = schemaClass.getIndexesInternal();
    for (var condition : flattenedConditions) {

      var indexedFunctConditions =
          condition.getIndexedFunctionConditions(schemaClass, session);

      var conditionEstimation = Long.MAX_VALUE;

      if (indexedFunctConditions != null) {
        for (var cond : indexedFunctConditions) {
          var from = new SQLFromClause(-1);
          from.item = new SQLFromItem(-1);
          from.item.setIdentifier(new SQLIdentifier(schemaClass.getName()));
          var newCount = cond.estimateIndexed(from, ctx);
          if (newCount < conditionEstimation) {
            conditionEstimation = newCount;
          }
        }
      } else {
        // Try histogram-based estimation first (handles equality, range,
        // IS NULL, BETWEEN, NOT, etc. without expensive index probes).
        for (var index : indexes) {
          var histEstimate = estimateConditionFromHistogram(
              session, index, condition, classCount, ctx);
          if (histEstimate >= 0 && histEstimate < conditionEstimation) {
            conditionEstimation = histEstimate;
          }
        }

        // Fall back to expensive index probes for equality conditions
        // when no histogram is available.
        if (conditionEstimation == Long.MAX_VALUE) {
          var conditions = getEqualityOperations(condition, ctx);

          for (var index : indexes) {
            var indexedFields = index.getDefinition().getProperties();
            var nMatchingKeys = 0;
            for (var indexedField : indexedFields) {
              if (conditions.containsKey(indexedField)) {
                nMatchingKeys++;
              } else {
                break;
              }
            }
            if (nMatchingKeys > 0) {
              var newCount =
                  estimateFromIndex(session, index, conditions, nMatchingKeys);
              if (newCount < conditionEstimation) {
                conditionEstimation = newCount;
              }
            }
          }
        }
      }
      if (conditionEstimation > count) {
        return count;
      }
      indexesCount += conditionEstimation;
    }
    return Math.min(indexesCount, count);
  }

  private static long estimateFromIndex(
      DatabaseSessionEmbedded session, Index index, Map<String, Object> conditions,
      int nMatchingKeys) {
    if (nMatchingKeys < 1) {
      throw new IllegalArgumentException("Cannot estimate from an index with zero keys");
    }
    var definition = index.getDefinition();
    var definitionFields = definition.getProperties();
    Object key = null;
    if (definition instanceof PropertyIndexDefinition) {
      key = convert(session, conditions.get(definitionFields.getFirst()), definition.getTypes()[0]);
    } else if (definition instanceof CompositeIndexDefinition) {
      key = new CompositeKey();
      for (var i = 0; i < nMatchingKeys; i++) {
        var keyValue =
            convert(session, conditions.get(definitionFields.get(i)), definition.getTypes()[i]);
        ((CompositeKey) key).addKey(keyValue);
      }
    }
    if (key != null) {
      if (conditions.size() == definitionFields.size()) {
        try (var rids = index.getRids(session, key)) {
          return rids.count();
        }
      } else {
        final Spliterator<RawPair<Object, RID>> spliterator;

        try (var stream =
            index.streamEntriesBetween(session, key, true, key, true, true)) {
          spliterator = stream.spliterator();
          return spliterator.estimateSize();
        }
      }
    }
    return Long.MAX_VALUE;
  }

  private static Object convert(DatabaseSessionEmbedded session, Object o,
      PropertyTypeInternal oType) {
    return PropertyTypeInternal.convert(session, o, oType.getDefaultJavaType());
  }

  private static Map<String, Object> getEqualityOperations(
      SQLAndBlock condition, CommandContext ctx) {
    Map<String, Object> result = new HashMap<>();
    for (var expression : condition.subBlocks) {
      if (expression instanceof SQLBinaryCondition b) {
        if (b.operator instanceof SQLEqualsOperator) {
          if (b.left.isBaseIdentifier() && b.right.isEarlyCalculated(ctx)) {
            result.put(b.left.toString(), b.right.execute((Result) null, ctx));
          }
        }
      }
    }
    return result;
  }

  /**
   * Estimates the number of matching rows for an AND block using the histogram
   * from the given index. Multiplies selectivities of matching predicates
   * (independence assumption per Section 7.3). Returns -1 if no predicate in
   * the block references the index's leading field, or if no statistics exist.
   */
  private static long estimateConditionFromHistogram(
      DatabaseSessionEmbedded session, Index index,
      SQLAndBlock condition, long classCount, CommandContext ctx) {
    var stats = index.getStatistics(session);
    if (stats == null || stats.totalCount() == 0) {
      return -1;
    }
    var histogram = index.getHistogram(session);
    var leadingField = index.getDefinition().getProperties().getFirst();

    // Detect two-sided range on the leading field (e.g., f > 20 AND f < 30)
    // and combine into a single estimateRange call for tighter estimates.
    var rangeResult = detectTwoSidedRange(
        condition, leadingField, stats, histogram, ctx);

    double selectivity = 1.0;
    boolean anyEstimated = false;

    if (rangeResult != null) {
      // Use the combined range selectivity and skip the two range predicates
      selectivity *= rangeResult.selectivity;
      anyEstimated = true;

      for (var expr : condition.subBlocks) {
        if (expr == rangeResult.lowerExpr || expr == rangeResult.upperExpr) {
          continue; // already accounted for by the combined range
        }
        var sel = estimatePredicateSelectivity(
            expr, leadingField, stats, histogram, ctx);
        if (sel >= 0) {
          selectivity *= sel;
        }
      }
    } else {
      // No two-sided range detected — estimate each predicate independently
      for (var expr : condition.subBlocks) {
        var sel = estimatePredicateSelectivity(
            expr, leadingField, stats, histogram, ctx);
        if (sel >= 0) {
          selectivity *= sel;
          anyEstimated = true;
        }
      }
    }

    if (!anyEstimated) {
      return -1;
    }
    // Note: selectivity is a fraction of non-null index entries (see
    // SelectivityEstimator Javadoc), but classCount includes all rows.
    // This produces a mild overestimate bounded by the null fraction —
    // an intentional conservative bias (see SelectivityEstimator class doc).
    return Math.max(1, (long) (classCount * selectivity));
  }

  /**
   * Result of detecting a two-sided range pattern in an AND block.
   */
  private record TwoSidedRange(
      SQLBooleanExpression lowerExpr,
      SQLBooleanExpression upperExpr,
      double selectivity
  ) {}

  /**
   * Scans the AND block's sub-blocks for a pair of binary conditions on
   * the same field where one is a lower bound (GT/GE) and the other is an
   * upper bound (LT/LE). Returns a {@link TwoSidedRange} with the combined
   * selectivity via {@link SelectivityEstimator#estimateRange}, or null if
   * no such pair is found.
   */
  @Nullable
  private static TwoSidedRange detectTwoSidedRange(
      SQLAndBlock condition, String indexField,
      IndexStatistics stats, @Nullable EquiDepthHistogram histogram,
      CommandContext ctx) {
    SQLBinaryCondition lower = null;
    SQLBinaryCondition upper = null;

    for (var expr : condition.subBlocks) {
      if (!(expr instanceof SQLBinaryCondition bc)) {
        continue;
      }
      if (!matchesField(bc.left, indexField)
          || !bc.right.isEarlyCalculated(ctx)) {
        continue;
      }
      var op = bc.operator;
      if (op instanceof SQLGtOperator || op instanceof SQLGeOperator) {
        if (lower == null) {
          lower = bc;
        }
      } else if (op instanceof SQLLtOperator || op instanceof SQLLeOperator) {
        if (upper == null) {
          upper = bc;
        }
      }
    }

    if (lower == null || upper == null) {
      return null;
    }

    var fromKey = lower.right.execute((Result) null, ctx);
    var toKey = upper.right.execute((Result) null, ctx);
    if (fromKey == null || toKey == null) {
      return null;
    }

    boolean fromInclusive = lower.operator instanceof SQLGeOperator;
    boolean toInclusive = upper.operator instanceof SQLLeOperator;
    double sel = SelectivityEstimator.estimateRange(
        stats, histogram, fromKey, toKey, fromInclusive, toInclusive);
    return new TwoSidedRange(lower, upper, sel);
  }

  /**
   * Estimates the selectivity of a single predicate using index statistics.
   * Returns -1 if the predicate does not reference the index field or cannot
   * be estimated.
   */
  private static double estimatePredicateSelectivity(
      SQLBooleanExpression expr, String indexField,
      IndexStatistics stats, @Nullable EquiDepthHistogram histogram,
      CommandContext ctx) {
    if (expr instanceof SQLBinaryCondition bc) {
      return estimateBinaryConditionSelectivity(
          bc, indexField, stats, histogram, ctx);
    }
    if (expr instanceof SQLBetweenCondition bt) {
      return estimateBetweenSelectivity(
          bt, indexField, stats, histogram, ctx);
    }
    if (expr instanceof SQLIsNullCondition nc) {
      if (matchesField(nc.expression, indexField)) {
        return SelectivityEstimator.estimateIsNull(stats, histogram);
      }
    }
    if (expr instanceof SQLIsNotNullCondition nnc) {
      if (matchesField(nnc.expression, indexField)) {
        return SelectivityEstimator.estimateIsNotNull(stats, histogram);
      }
    }
    if (expr instanceof SQLInCondition ic) {
      return estimateInConditionSelectivity(
          ic, indexField, stats, histogram, ctx);
    }
    if (expr instanceof SQLNotBlock nb && nb.negate) {
      var inner = estimatePredicateSelectivity(
          nb.sub, indexField, stats, histogram, ctx);
      return inner >= 0 ? 1.0 - inner : -1;
    }
    return -1;
  }

  /**
   * Dispatches a binary condition ({@code f op value}) to the appropriate
   * {@link SelectivityEstimator} method based on the operator type.
   */
  private static double estimateBinaryConditionSelectivity(
      SQLBinaryCondition bc, String indexField,
      IndexStatistics stats, @Nullable EquiDepthHistogram histogram,
      CommandContext ctx) {
    if (!matchesField(bc.left, indexField)
        || !bc.right.isEarlyCalculated(ctx)) {
      return -1;
    }
    var value = bc.right.execute((Result) null, ctx);
    if (value == null) {
      return -1;
    }

    var op = bc.operator;
    if (op instanceof SQLEqualsOperator) {
      return SelectivityEstimator.estimateEquality(stats, histogram, value);
    }
    if (op instanceof SQLGtOperator) {
      return SelectivityEstimator.estimateGreaterThan(
          stats, histogram, value);
    }
    if (op instanceof SQLLtOperator) {
      return SelectivityEstimator.estimateLessThan(
          stats, histogram, value);
    }
    if (op instanceof SQLGeOperator) {
      return SelectivityEstimator.estimateGreaterOrEqual(
          stats, histogram, value);
    }
    if (op instanceof SQLLeOperator) {
      return SelectivityEstimator.estimateLessOrEqual(
          stats, histogram, value);
    }
    if (op instanceof SQLNeOperator || op instanceof SQLNeqOperator) {
      var eqSel =
          SelectivityEstimator.estimateEquality(stats, histogram, value);
      return 1.0 - eqSel;
    }
    if (op instanceof SQLInOperator && value instanceof Collection<?> coll) {
      return SelectivityEstimator.estimateIn(stats, histogram, coll);
    }
    return -1;
  }

  /**
   * Estimates selectivity for {@code field BETWEEN lower AND upper}.
   */
  private static double estimateBetweenSelectivity(
      SQLBetweenCondition bt, String indexField,
      IndexStatistics stats, @Nullable EquiDepthHistogram histogram,
      CommandContext ctx) {
    if (!matchesField(bt.first, indexField)) {
      return -1;
    }
    if (!bt.second.isEarlyCalculated(ctx)
        || !bt.third.isEarlyCalculated(ctx)) {
      return -1;
    }
    var fromKey = bt.second.execute((Result) null, ctx);
    var toKey = bt.third.execute((Result) null, ctx);
    if (fromKey == null || toKey == null) {
      return -1;
    }
    return SelectivityEstimator.estimateRange(
        stats, histogram, fromKey, toKey, true, true);
  }

  /**
   * Estimates selectivity for {@code field IN (v1, v2, ..., vN)} expressed as
   * an {@link SQLInCondition}. The right-hand side may be a math expression
   * that evaluates to a collection, or a parameter.
   */
  private static double estimateInConditionSelectivity(
      SQLInCondition ic, String indexField,
      IndexStatistics stats, @Nullable EquiDepthHistogram histogram,
      CommandContext ctx) {
    if (ic.getLeft() == null || !matchesField(ic.getLeft(), indexField)) {
      return -1;
    }
    // The right side can be a math expression ([1,2,3]), a parameter (:param),
    // or a subquery. Only estimate when the value is early-calculable.
    var rightExpr = ic.getRightMathExpression();
    if (rightExpr == null || !rightExpr.isEarlyCalculated(ctx)) {
      // Try input parameter fallback
      if (ic.getRightParam() != null) {
        var paramValue = ic.getRightParam().getValue(ctx.getInputParameters());
        if (paramValue instanceof Collection<?> coll) {
          return SelectivityEstimator.estimateIn(stats, histogram, coll);
        }
      }
      return -1;
    }
    var value = rightExpr.execute((Result) null, ctx);
    if (value instanceof Collection<?> coll) {
      return SelectivityEstimator.estimateIn(stats, histogram, coll);
    }
    return -1;
  }

  /**
   * Returns true if the expression is a simple field reference matching
   * the given index field name.
   */
  private static boolean matchesField(SQLExpression expr, String indexField) {
    return expr.isBaseIdentifier() && indexField.equals(expr.toString());
  }

  public List<SQLAndBlock> flatten(CommandContext ctx, SchemaClassInternal schemaClass) {
    if (this.baseExpression == null) {
      return Collections.emptyList();
    }
    if (flattened == null) {
      flattened = this.baseExpression.flatten(ctx, schemaClass);
    }
    // TODO remove false conditions (contraddictions)
    return flattened;
  }

  public boolean needsAliases(Set<String> aliases) {
    return this.baseExpression.needsAliases(aliases);
  }

  public void setBaseExpression(SQLBooleanExpression baseExpression) {
    this.baseExpression = baseExpression;
  }

  @Override
  public SQLWhereClause copy() {
    var result = new SQLWhereClause(-1);
    result.baseExpression = baseExpression.copy();
    result.flattened =
        Optional.ofNullable(flattened)
            .map(
                oAndBlocks -> {
                  try (var stream = oAndBlocks.stream()) {
                    return stream.map(SQLAndBlock::copy).collect(Collectors.toList());
                  }
                })
            .orElse(null);
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    var that = (SQLWhereClause) o;

    if (!Objects.equals(baseExpression, that.baseExpression)) {
      return false;
    }
    return Objects.equals(flattened, that.flattened);
  }

  @Override
  public int hashCode() {
    int result = Optional.ofNullable(baseExpression).map(Object::hashCode).orElse(0);
    result = 31 * result + (Optional.ofNullable(flattened).map(List::hashCode).orElse(0));
    return result;
  }

  public void extractSubQueries(SubQueryCollector collector) {
    if (baseExpression != null) {
      baseExpression.extractSubQueries(collector);
    }
    flattened = null;
  }

  public boolean refersToParent() {
    return baseExpression != null && baseExpression.refersToParent();
  }

  public SQLBooleanExpression getBaseExpression() {
    return baseExpression;
  }

  public List<SQLAndBlock> getFlattened() {
    return flattened;
  }

  public void setFlattened(List<SQLAndBlock> flattened) {
    this.flattened = flattened;
  }

  public Result serialize(DatabaseSessionEmbedded session) {
    var result = new ResultInternal(session);
    if (baseExpression != null) {
      result.setProperty("baseExpression", baseExpression.serialize(session));
    }
    if (flattened != null) {
      try (var stream = flattened.stream()) {
        result.setProperty(
            "flattened",
            stream.map(oAndBlock -> oAndBlock.serialize(session)).collect(Collectors.toList()));
      }
    }
    return result;
  }

  public void deserialize(Result fromResult) {
    if (fromResult.getProperty("baseExpression") != null) {
      baseExpression =
          SQLBooleanExpression.deserializeFromOResult(fromResult.getProperty("baseExpression"));
    }
    if (fromResult.getProperty("flattened") != null) {
      List<Result> ser = fromResult.getProperty("flattened");
      flattened = new ArrayList<>();
      for (var r : ser) {
        var block = new SQLAndBlock(-1);
        block.deserialize(r);
        flattened.add(block);
      }
    }
  }

  public boolean isCacheable(DatabaseSessionEmbedded session) {
    return baseExpression.isCacheable(session);
  }

  @Nullable
  public IndexCandidate findIndex(IndexFinder info, CommandContext ctx) {
    return this.baseExpression.findIndex(info, ctx);
  }
}
/* JavaCC - OriginalChecksum=e8015d01ce1ab2bc337062e9e3f2603e (do not edit this line) */
