/* Generated By:JavaCC: Do not edit this line. YouTrackDBSqlTreeConstants.java Version 7.0.13 */
package com.jetbrains.youtrackdb.internal.core.sql.parser;

public interface YouTrackDBSqlTreeConstants
{

  int JJTRID = 0;
  int JJTPARSE = 1;
  int JJTPARSESCRIPT = 2;
  int JJTPARSESERVERSTATEMENT = 3;
  int JJTSTRING = 4;
  int JJTIDENTIFIER = 5;
  int JJTINTEGER = 6;
  int JJTFLOATINGPOINT = 7;
  int JJTNUMBER = 8;
  int JJTSERVERSTATEMENT = 9;
  int JJTSTATEMENT = 10;
  int JJTSTATEMENTSEMICOLON = 11;
  int JJTSTATEMENTINTERNAL = 12;
  int JJTEXPRESSIONSTATEMENT = 13;
  int JJTQUERYSTATEMENT = 14;
  int JJTSELECTWITHOUTTARGETSTATEMENT = 15;
  int JJTSELECTSTATEMENT = 16;
  int JJTMATCHSTATEMENT = 17;
  int JJTDELETESTATEMENT = 18;
  int JJTDELETEVERTEXSTATEMENT = 19;
  int JJTDELETEEDGESTATEMENT = 20;
  int JJTDELETEEDGEBYRIDSTATEMENT = 21;
  int JJTDELETEEDGEFROMTOSTATEMENT = 22;
  int JJTDELETEEDGETOSTATEMENT = 23;
  int JJTDELETEEDGEVTOSTATEMENT = 24;
  int JJTDELETEEDGEWHERESTATEMENT = 25;
  int JJTUPDATEEDGESTATEMENT = 26;
  int JJTUPDATESTATEMENT = 27;
  int JJTUPDATEOPERATIONS = 28;
  int JJTUPDATEITEM = 29;
  int JJTUPDATEINCREMENTITEM = 30;
  int JJTUPDATEREMOVEITEM = 31;
  int JJTUPDATEPUTITEM = 32;
  int JJTINSERTSTATEMENT = 33;
  int JJTINSERTBODY = 34;
  int JJTCREATEVERTEXSTATEMENTEMPTYNOTARGET = 35;
  int JJTCREATEVERTEXSTATEMENT = 36;
  int JJTCREATEVERTEXSTATEMENTNOTARGET = 37;
  int JJTCREATEEDGESTATEMENT = 38;
  int JJTINPUTPARAMETER = 39;
  int JJTPOSITIONALPARAMETER = 40;
  int JJTNAMEDPARAMETER = 41;
  int JJTPROJECTION = 42;
  int JJTPROJECTIONITEM = 43;
  int JJTNESTEDPROJECTION = 44;
  int JJTNESTEDPROJECTIONITEM = 45;
  int JJTARRAYSELECTOR = 46;
  int JJTARRAYNUMBERSELECTOR = 47;
  int JJTARRAYSINGLEVALUESSELECTOR = 48;
  int JJTARRAYRANGESELECTOR = 49;
  int JJTALIAS = 50;
  int JJTRECORDATTRIBUTE = 51;
  int JJTFUNCTIONCALL = 52;
  int JJTMETHODCALL = 53;
  int JJTLEVELZEROIDENTIFIER = 54;
  int JJTSUFFIXIDENTIFIER = 55;
  int JJTBASEIDENTIFIER = 56;
  int JJTMODIFIER = 57;
  int JJTEXPRESSION = 58;
  int JJTARRAYCONCATEXPRESSION = 59;
  int JJTARRAYCONCATEXPRESSIONELEMENT = 60;
  int JJTMATHEXPRESSION = 61;
  int JJTFIRSTLEVELEXPRESSION = 62;
  int JJTPARENTHESISEXPRESSION = 63;
  int JJTBASEEXPRESSION = 64;
  int JJTFROMCLAUSE = 65;
  int JJTLETCLAUSE = 66;
  int JJTLETITEM = 67;
  int JJTFROMITEM = 68;
  int JJTMETADATAIDENTIFIER = 69;
  int JJTINDEXNAME = 70;
  int JJTWHERECLAUSE = 71;
  int JJTORBLOCK = 72;
  int JJTANDBLOCK = 73;
  int JJTNOTBLOCK = 74;
  int JJTPARENTHESISBLOCK = 75;
  int JJTCONDITIONBLOCK = 76;
  int JJTCOMPAREOPERATOR = 77;
  int JJTLTOPERATOR = 78;
  int JJTGTOPERATOR = 79;
  int JJTNEOPERATOR = 80;
  int JJTNEQOPERATOR = 81;
  int JJTGEOPERATOR = 82;
  int JJTLEOPERATOR = 83;
  int JJTLIKEOPERATOR = 84;
  int JJTLUCENEOPERATOR = 85;
  int JJTNEAROPERATOR = 86;
  int JJTWITHINOPERATOR = 87;
  int JJTSCANDOPERATOR = 88;
  int JJTCONTAINSKEYOPERATOR = 89;
  int JJTCONTAINSVALUEOPERATOR = 90;
  int JJTEQUALSCOMPAREOPERATOR = 91;
  int JJTRIGHTBINARYCONDITION = 92;
  int JJTBINARYCONDITION = 93;
  int JJTCONTAINSVALUECONDITION = 94;
  int JJTINSTANCEOFCONDITION = 95;
  int JJTBETWEENCONDITION = 96;
  int JJTISNULLCONDITION = 97;
  int JJTISNOTNULLCONDITION = 98;
  int JJTISDEFINEDCONDITION = 99;
  int JJTISNOTDEFINEDCONDITION = 100;
  int JJTCONTAINSCONDITION = 101;
  int JJTINOPERATOR = 102;
  int JJTINCONDITION = 103;
  int JJTNOTINCONDITION = 104;
  int JJTCONTAINSALLCONDITION = 105;
  int JJTCONTAINSANYCONDITION = 106;
  int JJTCONTAINSTEXTCONDITION = 107;
  int JJTMATCHESCONDITION = 108;
  int JJTORDERBY = 109;
  int JJTGROUPBY = 110;
  int JJTUNWIND = 111;
  int JJTLIMIT = 112;
  int JJTSKIP = 113;
  int JJTBATCH = 114;
  int JJTTIMEOUT = 115;
  int JJTWAIT = 116;
  int JJTRETRY = 117;
  int JJTCOLLECTION = 118;
  int JJTFETCHPLAN = 119;
  int JJTFETCHPLANITEM = 120;
  int JJTJSON = 121;
  int JJTMATCHEXPRESSION = 122;
  int JJTMATCHPATHITEM = 123;
  int JJTFIELDMATCHPATHITEM = 124;
  int JJTMATCHPATHITEMFIRST = 125;
  int JJTMULTIMATCHPATHITEM = 126;
  int JJTMULTIMATCHPATHITEMARROWS = 127;
  int JJTMATCHFILTER = 128;
  int JJTMATCHFILTERITEM = 129;
  int JJTOUTPATHITEM = 130;
  int JJTINPATHITEM = 131;
  int JJTBOTHPATHITEM = 132;
  int JJTOUTPATHITEMOPT = 133;
  int JJTINPATHITEMOPT = 134;
  int JJTBOTHPATHITEMOPT = 135;
  int JJTPROFILESTORAGESTATEMENT = 136;
  int JJTTRUNCATECLASSSTATEMENT = 137;
  int JJTCREATECLASSSTATEMENT = 138;
  int JJTALTERCLASSSTATEMENT = 139;
  int JJTDROPCLASSSTATEMENT = 140;
  int JJTIFNOTEXISTS = 141;
  int JJTCREATEPROPERTYSTATEMENT = 142;
  int JJTCREATEPROPERTYATTRIBUTESTATEMENT = 143;
  int JJTALTERPROPERTYSTATEMENT = 144;
  int JJTDROPPROPERTYSTATEMENT = 145;
  int JJTCREATEINDEXSTATEMENT = 146;
  int JJTREBUILDINDEXSTATEMENT = 147;
  int JJTDROPINDEXSTATEMENT = 148;
  int JJTALTERDATABASESTATEMENT = 149;
  int JJTCOMMANDLINEOPTION = 150;
  int JJTOPTIMIZEDATABASESTATEMENT = 151;
  int JJTCREATELINKSTATEMENT = 152;
  int JJTEXPLAINSTATEMENT = 153;
  int JJTPROFILESTATEMENT = 154;
  int JJTPERMISSION = 155;
  int JJTGRANTSTATEMENT = 156;
  int JJTREVOKESTATEMENT = 157;
  int JJTCREATEFUNCTIONSTATEMENT = 158;
  int JJTCREATESYSTEMUSERSTATEMENT = 159;
  int JJTEXISTSSYSTEMUSERSTATEMENT = 160;
  int JJTCREATEUSERSTATEMENT = 161;
  int JJTDROPUSERSTATEMENT = 162;
  int JJTALTERROLESTATEMENT = 163;
  int JJTALTERSYSTEMROLESTATEMENT = 164;
  int JJTLETSTATEMENT = 165;
  int JJTBEGINSTATEMENT = 166;
  int JJTCOMMITSTATEMENT = 167;
  int JJTROLLBACKSTATEMENT = 168;
  int JJTRETURNSTATEMENT = 169;
  int JJTIFSTATEMENT = 170;
  int JJTSLEEPSTATEMENT = 171;
  int JJTCONSOLESTATEMENT = 172;
  int JJTCREATESEQUENCESTATEMENT = 173;
  int JJTALTERSEQUENCESTATEMENT = 174;
  int JJTDROPSEQUENCESTATEMENT = 175;
  int JJTFOREACHBLOCK = 176;
  int JJTWHILEBLOCK = 177;
  int JJTSECURITYRESOURCESEGMENT = 178;
  int JJTCREATESECURITYPOLICYSTATEMENT = 179;
  int JJTALTERSECURITYPOLICYSTATEMENT = 180;
  int JJTDATABASEUSERDATA = 181;
  int JJTCREATEDATABASESTATEMENT = 182;
  int JJTDROPDATABASESTATEMENT = 183;


  String[] jjtNodeName = {
    "Rid",
    "parse",
    "parseScript",
    "parseServerStatement",
    "String",
    "Identifier",
    "Integer",
    "FloatingPoint",
    "Number",
    "ServerStatement",
    "Statement",
    "StatementSemicolon",
    "StatementInternal",
    "ExpressionStatement",
    "QueryStatement",
    "SelectWithoutTargetStatement",
    "SelectStatement",
    "MatchStatement",
    "DeleteStatement",
    "DeleteVertexStatement",
    "DeleteEdgeStatement",
    "DeleteEdgeByRidStatement",
    "DeleteEdgeFromToStatement",
    "DeleteEdgeToStatement",
    "DeleteEdgeVToStatement",
    "DeleteEdgeWhereStatement",
    "UpdateEdgeStatement",
    "UpdateStatement",
    "UpdateOperations",
    "UpdateItem",
    "UpdateIncrementItem",
    "UpdateRemoveItem",
    "UpdatePutItem",
    "InsertStatement",
    "InsertBody",
    "CreateVertexStatementEmptyNoTarget",
    "CreateVertexStatement",
    "CreateVertexStatementNoTarget",
    "CreateEdgeStatement",
    "InputParameter",
    "PositionalParameter",
    "NamedParameter",
    "Projection",
    "ProjectionItem",
    "NestedProjection",
    "NestedProjectionItem",
    "ArraySelector",
    "ArrayNumberSelector",
    "ArraySingleValuesSelector",
    "ArrayRangeSelector",
    "Alias",
    "RecordAttribute",
    "FunctionCall",
    "MethodCall",
    "LevelZeroIdentifier",
    "SuffixIdentifier",
    "BaseIdentifier",
    "Modifier",
    "Expression",
    "ArrayConcatExpression",
    "ArrayConcatExpressionElement",
    "MathExpression",
    "FirstLevelExpression",
    "ParenthesisExpression",
    "BaseExpression",
    "FromClause",
    "LetClause",
    "LetItem",
    "FromItem",
    "MetadataIdentifier",
    "IndexName",
    "WhereClause",
    "OrBlock",
    "AndBlock",
    "NotBlock",
    "ParenthesisBlock",
    "ConditionBlock",
    "CompareOperator",
    "LtOperator",
    "GtOperator",
    "NeOperator",
    "NeqOperator",
    "GeOperator",
    "LeOperator",
    "LikeOperator",
    "LuceneOperator",
    "NearOperator",
    "WithinOperator",
    "ScAndOperator",
    "ContainsKeyOperator",
    "ContainsValueOperator",
    "EqualsCompareOperator",
    "RightBinaryCondition",
    "BinaryCondition",
    "ContainsValueCondition",
    "InstanceofCondition",
    "BetweenCondition",
    "IsNullCondition",
    "IsNotNullCondition",
    "IsDefinedCondition",
    "IsNotDefinedCondition",
    "ContainsCondition",
    "InOperator",
    "InCondition",
    "NotInCondition",
    "ContainsAllCondition",
    "ContainsAnyCondition",
    "ContainsTextCondition",
    "MatchesCondition",
    "OrderBy",
    "GroupBy",
    "Unwind",
    "Limit",
    "Skip",
    "Batch",
    "Timeout",
    "Wait",
    "Retry",
    "Collection",
    "FetchPlan",
    "FetchPlanItem",
    "Json",
    "MatchExpression",
    "MatchPathItem",
    "FieldMatchPathItem",
    "MatchPathItemFirst",
    "MultiMatchPathItem",
    "MultiMatchPathItemArrows",
    "MatchFilter",
    "MatchFilterItem",
    "OutPathItem",
    "InPathItem",
    "BothPathItem",
    "OutPathItemOpt",
    "InPathItemOpt",
    "BothPathItemOpt",
    "ProfileStorageStatement",
    "TruncateClassStatement",
    "CreateClassStatement",
    "AlterClassStatement",
    "DropClassStatement",
    "IfNotExists",
    "CreatePropertyStatement",
    "CreatePropertyAttributeStatement",
    "AlterPropertyStatement",
    "DropPropertyStatement",
    "CreateIndexStatement",
    "RebuildIndexStatement",
    "DropIndexStatement",
    "AlterDatabaseStatement",
    "CommandLineOption",
    "OptimizeDatabaseStatement",
    "CreateLinkStatement",
    "ExplainStatement",
    "ProfileStatement",
    "Permission",
    "GrantStatement",
    "RevokeStatement",
    "CreateFunctionStatement",
    "CreateSystemUserStatement",
    "ExistsSystemUserStatement",
    "CreateUserStatement",
    "DropUserStatement",
    "AlterRoleStatement",
    "AlterSystemRoleStatement",
    "LetStatement",
    "BeginStatement",
    "CommitStatement",
    "RollbackStatement",
    "ReturnStatement",
    "IfStatement",
    "SleepStatement",
    "ConsoleStatement",
    "CreateSequenceStatement",
    "AlterSequenceStatement",
    "DropSequenceStatement",
    "ForEachBlock",
    "WhileBlock",
    "SecurityResourceSegment",
    "CreateSecurityPolicyStatement",
    "AlterSecurityPolicyStatement",
    "DatabaseUserData",
    "CreateDatabaseStatement",
    "DropDatabaseStatement",
  };
}
/* JavaCC - OriginalChecksum=5c347991fbb8fa953fcd79ffda8f473f (do not edit this line) */
