package com.jetbrains.youtrackdb.internal.core.gremlin.gremlintest.scenarios;

import static org.apache.tinkerpop.gremlin.LoadGraphWith.GraphData.MODERN;
import static org.assertj.core.api.AssertionsForClassTypes.assertThat;

import com.jetbrains.youtrackdb.internal.common.profiler.monitoring.QueryMetricsListener;
import com.jetbrains.youtrackdb.internal.common.profiler.monitoring.QueryMonitoringMode;
import com.jetbrains.youtrackdb.internal.common.profiler.monitoring.TransactionMetricsListener;
import com.jetbrains.youtrackdb.internal.core.YouTrackDBEnginesManager;
import com.jetbrains.youtrackdb.internal.core.gremlin.YTDBTransaction;
import org.apache.tinkerpop.gremlin.LoadGraphWith;
import org.apache.tinkerpop.gremlin.process.GremlinProcessRunner;
import org.junit.BeforeClass;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(GremlinProcessRunner.class)
public class YTDBTransactionMetricsListenerTest extends YTDBAbstractGremlinTest {

  private static long TICKER_POSSIBLE_LAG_NANOS;
  private static long TICKER_POSSIBLE_LAG_MILLIS;

  @BeforeClass
  public static void beforeClass() throws InterruptedException {
    var granularity =
        YouTrackDBEnginesManager.instance().getTicker().getGranularity();
    TICKER_POSSIBLE_LAG_NANOS = granularity * 3;
    TICKER_POSSIBLE_LAG_MILLIS = TICKER_POSSIBLE_LAG_NANOS / 1_000_000;

    // Ensure ticker has had time to stabilize after graph setup.
    Thread.sleep(100);
  }

  // 3.1. Basic commit callback — write transaction triggers listener exactly once.
  @Test
  @LoadGraphWith(MODERN)
  public void writeTransactionCallsListener() {
    var listener = new RememberingTxListener();
    var beforeMillis = System.currentTimeMillis();

    var tx = ytdbTx()
        .withQueryMonitoringMode(QueryMonitoringMode.EXACT)
        .withTransactionListener(listener);
    tx.open();
    g().addV("TestVertex").property("name", "test").iterate();
    tx.commit();

    var afterMillis = System.currentTimeMillis();

    assertThat(listener.callCount).isEqualTo(1);
    assertThat(listener.commitAtMillis)
        .isGreaterThanOrEqualTo(beforeMillis)
        .isLessThanOrEqualTo(afterMillis);
    assertThat(listener.commitTimeNanos).isGreaterThan(0);
  }

  // 3.2. Read-only transaction — listener is NOT called.
  @Test
  @LoadGraphWith(MODERN)
  public void readOnlyTransactionDoesNotCallListener() {
    var listener = new RememberingTxListener();

    var tx = ytdbTx()
        .withQueryMonitoringMode(QueryMonitoringMode.EXACT)
        .withTransactionListener(listener);
    tx.open();
    g().V().hasLabel("person").toList();
    tx.commit();

    assertThat(listener.callCount).isEqualTo(0);
  }

  // 3.3. Empty transaction — listener is NOT called.
  @Test
  @LoadGraphWith(MODERN)
  public void emptyTransactionDoesNotCallListener() {
    var listener = new RememberingTxListener();

    var tx = ytdbTx()
        .withTransactionListener(listener);
    tx.open();
    tx.commit();

    assertThat(listener.callCount).isEqualTo(0);
  }

  // 3.4. Rollback — listener is NOT called.
  @Test
  @LoadGraphWith(MODERN)
  public void rollbackDoesNotCallListener() {
    var listener = new RememberingTxListener();

    var tx = ytdbTx()
        .withTransactionListener(listener);
    tx.open();
    g().addV("TestVertex").property("name", "rollbackMe").iterate();
    tx.rollback();

    assertThat(listener.callCount).isEqualTo(0);
  }

  // 3.6. Listener exception safety — buggy listener does not break the commit.
  @Test
  @LoadGraphWith(MODERN)
  public void listenerExceptionDoesNotBreakCommit() {
    TransactionMetricsListener throwingListener = (txDetails, commitAtMillis, commitTimeNanos) -> {
      throw new RuntimeException("Listener bug");
    };

    var tx = ytdbTx()
        .withTransactionListener(throwingListener);
    tx.open();
    g().addV("TestVertex").property("name", "safe").iterate();
    // Should not throw — the listener exception is caught internally.
    tx.commit();

    // Verify monitoring state was cleaned up (next tx doesn't carry the listener).
    assertThat(ytdbTx().isTransactionMetricsEnabled()).isFalse();
  }

  // 3.7. Tracking ID — explicit.
  @Test
  @LoadGraphWith(MODERN)
  public void explicitTrackingIdAppearsInDetails() {
    var listener = new RememberingTxListener();

    var tx = ytdbTx()
        .withTrackingId("my-tx-42")
        .withTransactionListener(listener);
    tx.open();
    g().addV("TestVertex").property("name", "tracked").iterate();
    tx.commit();

    assertThat(listener.trackingId).isEqualTo("my-tx-42");
  }

  // 3.8. Tracking ID — auto-generated.
  @Test
  @LoadGraphWith(MODERN)
  public void autoGeneratedTrackingIdIsPresent() {
    var listener = new RememberingTxListener();

    var tx = ytdbTx()
        .withTransactionListener(listener);
    tx.open();
    g().addV("TestVertex").property("name", "autoId").iterate();
    tx.commit();

    assertThat(listener.trackingId).isNotNull().isNotEmpty();
  }

  // 3.9. LIGHTWEIGHT mode — approximate timestamps.
  @Test
  @LoadGraphWith(MODERN)
  public void lightweightModeUsesApproximateTimestamps() {
    var listener = new RememberingTxListener();
    var beforeMillis = System.currentTimeMillis();

    var tx = ytdbTx()
        .withQueryMonitoringMode(QueryMonitoringMode.LIGHTWEIGHT)
        .withTransactionListener(listener);
    tx.open();
    g().addV("TestVertex").property("name", "lightweight").iterate();
    tx.commit();

    var afterMillis = System.currentTimeMillis();

    assertThat(listener.callCount).isEqualTo(1);
    // In lightweight mode, timestamps come from the ticker and may lag by up to
    // TICKER_POSSIBLE_LAG_MILLIS.
    assertThat(listener.commitAtMillis)
        .isGreaterThanOrEqualTo(beforeMillis - TICKER_POSSIBLE_LAG_MILLIS)
        .isLessThanOrEqualTo(afterMillis + TICKER_POSSIBLE_LAG_MILLIS);
    // In LIGHTWEIGHT mode, if the commit is faster than the ticker granularity, both the
    // start and end approximate nano times can be identical, yielding a zero duration.
    assertThat(listener.commitTimeNanos).isGreaterThanOrEqualTo(0);
  }

  // 3.9 (cont). EXACT mode — precise timestamps.
  @Test
  @LoadGraphWith(MODERN)
  public void exactModeUsesPreciseTimestamps() {
    var listener = new RememberingTxListener();
    var beforeMillis = System.currentTimeMillis();

    var tx = ytdbTx()
        .withQueryMonitoringMode(QueryMonitoringMode.EXACT)
        .withTransactionListener(listener);
    tx.open();
    g().addV("TestVertex").property("name", "exact").iterate();
    tx.commit();

    var afterMillis = System.currentTimeMillis();

    assertThat(listener.callCount).isEqualTo(1);
    assertThat(listener.commitAtMillis)
        .isGreaterThanOrEqualTo(beforeMillis)
        .isLessThanOrEqualTo(afterMillis);
    assertThat(listener.commitTimeNanos).isGreaterThan(0);
  }

  // 3.10. Listener cleanup on commit — next transaction doesn't carry the listener.
  @Test
  @LoadGraphWith(MODERN)
  public void listenerIsNotCarriedOverToNextTransaction() {
    var listener = new RememberingTxListener();

    var tx = ytdbTx()
        .withTransactionListener(listener);
    tx.open();
    g().addV("TestVertex").property("name", "first").iterate();
    tx.commit();

    assertThat(listener.callCount).isEqualTo(1);

    // Second transaction without re-registering the listener.
    tx.open();
    g().addV("TestVertex").property("name", "second").iterate();
    tx.commit();

    // Listener should not have been called again.
    assertThat(listener.callCount).isEqualTo(1);
  }

  // 3.11. Both listeners together — query and transaction listeners fire in same tx.
  @Test
  @LoadGraphWith(MODERN)
  public void bothListenersFireInSameTransaction() {
    var txListener = new RememberingTxListener();
    var queryListener = new RememberingQueryListener();

    var tx = ytdbTx()
        .withQueryMonitoringMode(QueryMonitoringMode.EXACT)
        .withQueryListener(queryListener)
        .withTransactionListener(txListener);
    tx.open();
    g().addV("TestVertex").property("name", "both").iterate();
    tx.commit();

    assertThat(txListener.callCount).isEqualTo(1);
    assertThat(queryListener.callCount).isGreaterThanOrEqualTo(1);
  }

  // 3.12. Multiple writes — listener fires exactly once.
  @Test
  @LoadGraphWith(MODERN)
  public void multipleWritesSingleCallback() {
    var listener = new RememberingTxListener();

    var tx = ytdbTx()
        .withTransactionListener(listener);
    tx.open();
    g().addV("TestVertex").property("name", "v1").iterate();
    g().addV("TestVertex").property("name", "v2").iterate();
    g().addV("TestVertex").property("name", "v3").iterate();
    tx.commit();

    assertThat(listener.callCount).isEqualTo(1);
  }

  private YTDBTransaction ytdbTx() {
    return (YTDBTransaction) g.tx();
  }

  // Single-threaded test helper — no synchronization needed.
  static class RememberingTxListener implements TransactionMetricsListener {

    int callCount;
    String trackingId;
    long commitAtMillis;
    long commitTimeNanos;

    @Override
    public void writeTransactionCommitted(
        TransactionDetails txDetails, long commitAtMillis, long commitTimeNanos) {
      this.callCount++;
      this.trackingId = txDetails.getTransactionTrackingId();
      this.commitAtMillis = commitAtMillis;
      this.commitTimeNanos = commitTimeNanos;
    }
  }

  static class RememberingQueryListener implements QueryMetricsListener {

    int callCount;

    @Override
    public void queryFinished(
        QueryDetails queryDetails, long startedAtMillis, long executionTimeNanos) {
      this.callCount++;
    }
  }
}
