package com.jetbrains.youtrack.db.auto;

import static org.testng.AssertJUnit.assertEquals;
import static org.testng.AssertJUnit.assertNotNull;
import static org.testng.AssertJUnit.assertNull;

import com.jetbrains.youtrack.db.api.DatabaseSession;
import com.jetbrains.youtrack.db.api.record.DBRecord;
import com.jetbrains.youtrack.db.api.record.Identifiable;
import com.jetbrains.youtrack.db.api.schema.PropertyType;
import com.jetbrains.youtrack.db.api.schema.Schema;
import com.jetbrains.youtrack.db.api.schema.SchemaClass;
import com.jetbrains.youtrack.db.internal.core.index.CompositeKey;
import com.jetbrains.youtrack.db.internal.core.record.impl.EntityImpl;
import java.util.Date;
import java.util.Set;
import org.testng.Assert;
import org.testng.annotations.Test;

/**
 * @since 3/3/2015
 */
public class DefaultValuesTrivialTest extends BaseDBTest {

  private static final int DOCUMENT_COUNT = 50;

  @Test
  public void test() {

    // create example schema
    Schema schema = session.getMetadata().getSchema();
    var classPerson = schema.createClass("PersonA");

    classPerson.createProperty("name", PropertyType.STRING);
    classPerson.createProperty("join_date", PropertyType.DATETIME)
        .setDefaultValue("sysdate()");
    classPerson.createProperty("active", PropertyType.BOOLEAN)
        .setDefaultValue("true");

    session.begin();
    var dtStart = getDatabaseSysdate(session);

    var docs = new EntityImpl[DOCUMENT_COUNT];
    for (var i = 0; i < DOCUMENT_COUNT; ++i) {
      var doc = ((EntityImpl) session.newEntity("PersonA"));
      doc.setProperty("name", "autoGeneratedName #" + i);

      docs[i] = doc;
    }
    session.commit();

    final var tx = session.begin();
    var dtAfter = getDatabaseSysdate(session);

    for (var i = 0; i < DOCUMENT_COUNT; ++i) {
      final var doc = tx.loadEntity(docs[i].getIdentity());

      try {
        //
        var dt = doc.getDateTime("join_date");

        var isInRange = (!dt.before(dtStart)) && (!dt.after(dtAfter));
        Assert.assertTrue(isInRange);

        //
        boolean active = doc.getBoolean("active");
        Assert.assertTrue(active);
      } catch (Exception ex) {
        ex.printStackTrace();
        Assert.fail();
      }
    }
    session.commit();
  }

  private static Date getDatabaseSysdate(DatabaseSession database) {
    return database.computeInTx(transaction -> {
      try (var dates = transaction.query("SELECT sysdate() as sysdate")) {
        return dates.next().getProperty("sysdate");
      }
    });
  }

  @Test
  public void testDefaultValueConversion() {
    session.begin();
    final var userId = session.getCurrentUser().getIdentity();
    session.commit();

    Schema schema = session.getMetadata().getSchema();

    var classPerson = schema.createClass("PersonB");
    classPerson.createProperty("users", PropertyType.LINKSET)
        .setDefaultValue("[" + userId + "]");

    session.begin();
    var doc = ((EntityImpl) session.newEntity("PersonB"));
    var record = (DBRecord) doc;
    session.commit();

    session.begin();
    EntityImpl doc1 = session.load(record.getIdentity());
    Set<Identifiable> rids = doc1.getProperty("users");
    assertEquals(rids.size(), 1);
    assertEquals(rids.iterator().next(), userId);
    session.commit();
  }

  @Test
  public void testPrepopulation() {
    // create example schema
    Schema schema = session.getMetadata().getSchema();
    var classA = schema.createClass("ClassA");

    classA.createProperty("name", PropertyType.STRING)
        .setDefaultValue("default name");
    classA.createProperty("date", PropertyType.DATETIME)
        .setDefaultValue("sysdate()");
    classA.createProperty("active", PropertyType.BOOLEAN)
        .setDefaultValue("true");

    session.executeInTx(tx -> {
      var doc = ((EntityImpl) session.newEntity(classA));
      assertEquals("default name", doc.getProperty("name"));
      assertNotNull(doc.getProperty("date"));
      assertEquals((Boolean) true, doc.getProperty("active"));
    });

    session.executeInTx(tx -> {
      var doc = ((EntityImpl) session.newEntity(classA.getName()));
      assertEquals("default name", doc.getProperty("name"));
      assertNotNull(doc.getProperty("date"));
      assertEquals((Boolean) true, doc.getProperty("active"));
    });

    session.executeInTx(tx -> {
      var doc = ((EntityImpl) session.newEntity());
      assertNull(doc.getProperty("name"));
      assertNull(doc.getProperty("date"));
      assertNull(doc.getProperty("active"));
      doc.setClassNameIfExists(classA.getName());
      assertEquals("default name", doc.getProperty("name"));
      assertNotNull(doc.getProperty("date"));
      assertEquals((Boolean) true, doc.getProperty("active"));
    });
  }

  @Test
  public void testPrepopulationIndex() {
    // create example schema
    Schema schema = session.getMetadata().getSchema();
    var classB = schema.createClass("ClassB");

    var prop = classB.createProperty("name", PropertyType.STRING);
    prop.setDefaultValue("default name");
    prop.createIndex(SchemaClass.INDEX_TYPE.NOTUNIQUE);

    session.executeInTx(tx -> {
      var doc = ((EntityImpl) session.newEntity(classB));
      assertEquals("default name", doc.getProperty("name"));
    });

    try (var stream = session.getIndex("ClassB.name")
        .getRids(session, "default name")) {
      assertEquals(1, stream.count());
    }
  }

  @Test
  public void testPrepopulationMultivalueIndex() {

    // create example schema
    Schema schema = session.getMetadata().getSchema();
    var classD = schema.createClass("ClassD");

    var prop = classD.createProperty("name", PropertyType.STRING);
    prop.setDefaultValue("default name");
    classD.createProperty("value", PropertyType.STRING);
    classD.createIndex("multi", SchemaClass.INDEX_TYPE.NOTUNIQUE, "value",
        "name");
    var index = session.getIndex("multi");

    {
      session.begin();
      var doc = ((EntityImpl) session.newEntity(classD));
      assertEquals("default name", doc.getProperty("name"));
      doc.setProperty("value", "1");

      session.commit();

      try (var stream = index.getRids(session, new CompositeKey("1"))) {
        assertEquals(1, stream.count());
      }
    }
    {
      session.begin();
      var doc = ((EntityImpl) session.newEntity(classD));
      assertEquals("default name", doc.getProperty("name"));
      doc.setProperty("value", "2");

      session.commit();

      try (var stream = index.getRids(session, new CompositeKey("2"))) {
        assertEquals(1, stream.count());
      }
    }
    try (var stream = index.getRids(session, new CompositeKey("3"))) {
      assertEquals(0, stream.count());
    }
  }
}
