package com.jetbrains.youtrackdb.auto;

import static org.testng.AssertJUnit.assertEquals;
import static org.testng.AssertJUnit.assertNotNull;
import static org.testng.AssertJUnit.assertNull;

import com.jetbrains.youtrackdb.api.DatabaseSession;
import com.jetbrains.youtrackdb.api.gremlin.__;
import com.jetbrains.youtrackdb.api.gremlin.embedded.domain.YTDBSchemaIndex.IndexType;
import com.jetbrains.youtrackdb.api.record.DBRecord;
import com.jetbrains.youtrackdb.api.record.Identifiable;
import com.jetbrains.youtrackdb.api.schema.PropertyType;
import com.jetbrains.youtrackdb.internal.common.collection.YTDBIteratorUtils;
import com.jetbrains.youtrackdb.internal.core.index.CompositeKey;
import com.jetbrains.youtrackdb.internal.core.record.impl.EntityImpl;
import java.util.Date;
import java.util.Set;
import org.testng.Assert;
import org.testng.annotations.Test;

/**
 * @since 3/3/2015
 */
public class DefaultValuesTrivialTest extends BaseDBTest {

  private static final int DOCUMENT_COUNT = 50;

  @Test
  public void test() {
    // create example schema
    graph.autoExecuteInTx(g ->
        g.createSchemaClass("PersonA",
            __.createSchemaProperty("name", PropertyType.STRING),
            __.createSchemaProperty("join_date", PropertyType.DATETIME)
                .defaultValueAttr("sysdate()"),
            __.createSchemaProperty("active", PropertyType.BOOLEAN)
                .defaultValueAttr("true")
        )
    );

    session.begin();
    var dtStart = getDatabaseSysdate(session);

    var docs = new EntityImpl[DOCUMENT_COUNT];
    for (var i = 0; i < DOCUMENT_COUNT; ++i) {
      var doc = ((EntityImpl) session.newEntity("PersonA"));
      doc.setProperty("name", "autoGeneratedName #" + i);

      docs[i] = doc;
    }
    session.commit();

    final var tx = session.begin();
    var dtAfter = getDatabaseSysdate(session);

    for (var i = 0; i < DOCUMENT_COUNT; ++i) {
      final var doc = tx.loadEntity(docs[i].getIdentity());

      try {
        //
        var dt = doc.getDateTime("join_date");

        var isInRange = (!dt.before(dtStart)) && (!dt.after(dtAfter));
        Assert.assertTrue(isInRange);

        //
        boolean active = doc.getBoolean("active");
        Assert.assertTrue(active);
      } catch (Exception ex) {
        ex.printStackTrace();
        Assert.fail();
      }
    }
    session.commit();
  }

  private static Date getDatabaseSysdate(DatabaseSession database) {
    return database.computeInTx(transaction -> {
      try (var dates = transaction.query("SELECT sysdate() as sysdate")) {
        return dates.next().getProperty("sysdate");
      }
    });
  }

  @Test
  public void testDefaultValueConversion() {
    session.begin();
    final var userId = session.getCurrentUser().getIdentity();
    session.commit();

    graph.autoExecuteInTx(g ->
        g.createSchemaClass("PersonB",
            __.createSchemaProperty("users", PropertyType.LINKSET)
                .defaultValueAttr("[" + userId + "]")
        )
    );

    session.begin();
    var doc = ((EntityImpl) session.newEntity("PersonB"));
    var record = (DBRecord) doc;
    session.commit();

    session.begin();
    EntityImpl doc1 = session.load(record.getIdentity());
    Set<Identifiable> rids = doc1.getProperty("users");
    assertEquals(1, rids.size());
    assertEquals(rids.iterator().next(), userId);
    session.commit();
  }

  @Test
  public void testPrepopulation() {
    // create example schema
    graph.autoExecuteInTx(g ->
        g.createSchemaClass("ClassA",
            __.createSchemaProperty("name", PropertyType.STRING)
                .defaultValueAttr("default name"),
            __.createSchemaProperty("date", PropertyType.DATETIME)
                .defaultValueAttr("sysdate()"),
            __.createSchemaProperty("active", PropertyType.BOOLEAN)
                .defaultValueAttr("true")
        )
    );

    session.executeInTx(tx -> {
      var doc = ((EntityImpl) session.newEntity("ClassA"));
      assertEquals("default name", doc.getProperty("name"));
      assertNotNull(doc.getProperty("date"));
      assertEquals((Boolean) true, doc.getProperty("active"));
    });

    session.executeInTx(tx -> {
      var doc = ((EntityImpl) session.newEntity("ClassA"));
      assertEquals("default name", doc.getProperty("name"));
      assertNotNull(doc.getProperty("date"));
      assertEquals((Boolean) true, doc.getProperty("active"));
    });

    session.executeInTx(tx -> {
      var doc = ((EntityImpl) session.newEntity());
      assertNull(doc.getProperty("name"));
      assertNull(doc.getProperty("date"));
      assertNull(doc.getProperty("active"));
      doc.setClassNameIfExists("ClassA");
      assertEquals("default name", doc.getProperty("name"));
      assertNotNull(doc.getProperty("date"));
      assertEquals((Boolean) true, doc.getProperty("active"));
    });
  }

  @Test
  public void testPrepopulationIndex() {
    // create example schema
    graph.autoExecuteInTx(g ->
        g.createSchemaClass("ClassB",
            __.createSchemaProperty("name", PropertyType.STRING)
                .defaultValueAttr("default name")
                .createPropertyIndex(IndexType.NOT_UNIQUE)
        )
    );

    session.executeInTx(tx -> {
      var doc = ((EntityImpl) session.newEntity("ClassB"));
      assertEquals("default name", doc.getProperty("name"));
    });

    try (var iterator = session.getMetadata().getFastImmutableSchemaSnapshot()
        .getIndex("ClassB.name")
        .getRids(session, "default name")) {
      assertEquals(1, YTDBIteratorUtils.count(iterator));
    }
  }

  @Test
  public void testPrepopulationMultivalueIndex() {
    // create example schema

    graph.autoExecuteInTx(g ->
        g.createSchemaClass("ClassD",
            __.createSchemaProperty("name", PropertyType.STRING).defaultValueAttr("default name"),
            __.createSchemaProperty("value", PropertyType.STRING)
        ).createClassIndex("multi", IndexType.NOT_UNIQUE, "value", "name")
    );

    var index = session.getMetadata().getFastImmutableSchemaSnapshot().getIndex("multi");
    {
      session.begin();
      var doc = ((EntityImpl) session.newEntity("ClassD"));
      assertEquals("default name", doc.getProperty("name"));
      doc.setProperty("value", "1");

      session.commit();

      try (var iterator = index.getRids(session, new CompositeKey("1"))) {
        assertEquals(1, YTDBIteratorUtils.count(iterator));
      }
    }
    {
      session.begin();
      var doc = ((EntityImpl) session.newEntity("ClassD"));
      assertEquals("default name", doc.getProperty("name"));
      doc.setProperty("value", "2");

      session.commit();

      try (var iterator = index.getRids(session, new CompositeKey("2"))) {
        assertEquals(1, YTDBIteratorUtils.count(iterator));
      }
    }
    try (var iterator = index.getRids(session, new CompositeKey("3"))) {
      assertEquals(0, YTDBIteratorUtils.count(iterator));
    }
  }
}
