/*
 *
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.jetbrains.youtrackdb.auto.junit;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;

import com.jetbrains.youtrackdb.internal.core.db.DatabaseSession;
import com.jetbrains.youtrackdb.internal.core.db.record.record.DBRecord;
import com.jetbrains.youtrackdb.internal.core.db.record.record.Identifiable;
import com.jetbrains.youtrackdb.internal.core.index.CompositeKey;
import com.jetbrains.youtrackdb.internal.core.metadata.schema.schema.PropertyType;
import com.jetbrains.youtrackdb.internal.core.metadata.schema.schema.Schema;
import com.jetbrains.youtrackdb.internal.core.metadata.schema.schema.SchemaClass;
import com.jetbrains.youtrackdb.internal.core.record.impl.EntityImpl;
import java.util.Date;
import java.util.Set;
import org.junit.Assert;
import org.junit.BeforeClass;
import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

/**
 * JUnit 4 migration of DefaultValuesTrivialTest. Original test class:
 * com.jetbrains.youtrackdb.auto.DefaultValuesTrivialTest Location:
 * tests/src/test/java/com/jetbrains/youtrackdb/auto/DefaultValuesTrivialTest.java
 *
 * @since 3/3/2015
 */
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class DefaultValuesTrivialTest extends BaseDBTest {

  private static final int DOCUMENT_COUNT = 50;

  @BeforeClass
  public static void setUpClass() throws Exception {
    DefaultValuesTrivialTest instance = new DefaultValuesTrivialTest();
    instance.beforeClass();
  }

  /**
   * Original test method: test Location:
   * tests/src/test/java/com/jetbrains/youtrackdb/auto/DefaultValuesTrivialTest.java:27
   */
  @Test
  public void test01_Test() {
    // create example schema
    Schema schema = session.getMetadata().getSchema();
    var classPerson = schema.createClass("PersonA");

    classPerson.createProperty("name", PropertyType.STRING);
    classPerson.createProperty("join_date", PropertyType.DATETIME)
        .setDefaultValue("sysdate()");
    classPerson.createProperty("active", PropertyType.BOOLEAN)
        .setDefaultValue("true");

    session.begin();
    var dtStart = getDatabaseSysdate(session);

    var docs = new EntityImpl[DOCUMENT_COUNT];
    for (var i = 0; i < DOCUMENT_COUNT; ++i) {
      var doc = ((EntityImpl) session.newEntity("PersonA"));
      doc.setProperty("name", "autoGeneratedName #" + i);

      docs[i] = doc;
    }
    session.commit();

    final var tx = session.begin();
    var dtAfter = getDatabaseSysdate(session);

    for (var i = 0; i < DOCUMENT_COUNT; ++i) {
      final var doc = tx.loadEntity(docs[i].getIdentity());

      try {
        //
        var dt = doc.getDateTime("join_date");

        var isInRange = (!dt.before(dtStart)) && (!dt.after(dtAfter));
        Assert.assertTrue(isInRange);

        //
        boolean active = doc.getBoolean("active");
        Assert.assertTrue(active);
      } catch (Exception ex) {
        ex.printStackTrace();
        Assert.fail();
      }
    }
    session.commit();
  }

  /**
   * Original helper method: getDatabaseSysdate Location:
   * tests/src/test/java/com/jetbrains/youtrackdb/auto/DefaultValuesTrivialTest.java:76
   */
  private static Date getDatabaseSysdate(DatabaseSession database) {
    return database.computeInTx(transaction -> {
      try (var dates = transaction.query("SELECT sysdate() as sysdate")) {
        return dates.next().getProperty("sysdate");
      }
    });
  }

  /**
   * Original test method: testDefaultValueConversion Location:
   * tests/src/test/java/com/jetbrains/youtrackdb/auto/DefaultValuesTrivialTest.java:84
   */
  @Test
  public void test02_DefaultValueConversion() {
    session.begin();
    final var userId = session.getCurrentUser().getIdentity();
    session.commit();

    Schema schema = session.getMetadata().getSchema();

    var classPerson = schema.createClass("PersonB");
    classPerson.createProperty("users", PropertyType.LINKSET)
        .setDefaultValue("[" + userId + "]");

    session.begin();
    var doc = ((EntityImpl) session.newEntity("PersonB"));
    var record = (DBRecord) doc;
    session.commit();

    session.begin();
    EntityImpl doc1 = session.load(record.getIdentity());
    Set<Identifiable> rids = doc1.getProperty("users");
    assertEquals(1, rids.size());
    assertEquals(userId, rids.iterator().next());
    session.commit();
  }

  /**
   * Original test method: testPrepopulation Location:
   * tests/src/test/java/com/jetbrains/youtrackdb/auto/DefaultValuesTrivialTest.java:109
   */
  @Test
  public void test03_Prepopulation() {
    // create example schema
    Schema schema = session.getMetadata().getSchema();
    var classA = schema.createClass("ClassA");

    classA.createProperty("name", PropertyType.STRING)
        .setDefaultValue("default name");
    classA.createProperty("date", PropertyType.DATETIME)
        .setDefaultValue("sysdate()");
    classA.createProperty("active", PropertyType.BOOLEAN)
        .setDefaultValue("true");

    session.executeInTx(tx -> {
      var doc = ((EntityImpl) session.newEntity(classA));
      assertEquals("default name", doc.getProperty("name"));
      assertNotNull(doc.getProperty("date"));
      assertEquals((Boolean) true, doc.getProperty("active"));
    });

    session.executeInTx(tx -> {
      var doc = ((EntityImpl) session.newEntity(classA.getName()));
      assertEquals("default name", doc.getProperty("name"));
      assertNotNull(doc.getProperty("date"));
      assertEquals((Boolean) true, doc.getProperty("active"));
    });

    session.executeInTx(tx -> {
      var doc = ((EntityImpl) session.newEntity());
      assertNull(doc.getProperty("name"));
      assertNull(doc.getProperty("date"));
      assertNull(doc.getProperty("active"));
      doc.setClassNameIfExists(classA.getName());
      assertEquals("default name", doc.getProperty("name"));
      assertNotNull(doc.getProperty("date"));
      assertEquals((Boolean) true, doc.getProperty("active"));
    });
  }

  /**
   * Original test method: testPrepopulationIndex Location:
   * tests/src/test/java/com/jetbrains/youtrackdb/auto/DefaultValuesTrivialTest.java:148
   */
  @Test
  public void test04_PrepopulationIndex() {
    // create example schema
    Schema schema = session.getMetadata().getSchema();
    var classB = schema.createClass("ClassB");

    var prop = classB.createProperty("name", PropertyType.STRING);
    prop.setDefaultValue("default name");
    prop.createIndex(SchemaClass.INDEX_TYPE.NOTUNIQUE);

    session.executeInTx(tx -> {
      var doc = ((EntityImpl) session.newEntity(classB));
      assertEquals("default name", doc.getProperty("name"));
    });

    try (var stream = session.getIndex("ClassB.name")
        .getRids(session, "default name")) {
      assertEquals(1, stream.count());
    }
  }

  /**
   * Original test method: testPrepopulationMultivalueIndex Location:
   * tests/src/test/java/com/jetbrains/youtrackdb/auto/DefaultValuesTrivialTest.java:169
   */
  @Test
  public void test05_PrepopulationMultivalueIndex() {
    // create example schema
    Schema schema = session.getMetadata().getSchema();
    var classD = schema.createClass("ClassD");

    var prop = classD.createProperty("name", PropertyType.STRING);
    prop.setDefaultValue("default name");
    classD.createProperty("value", PropertyType.STRING);
    classD.createIndex("multi", SchemaClass.INDEX_TYPE.NOTUNIQUE, "value",
        "name");
    var index = session.getIndex("multi");

    {
      session.begin();
      var doc = ((EntityImpl) session.newEntity(classD));
      assertEquals("default name", doc.getProperty("name"));
      doc.setProperty("value", "1");

      session.commit();

      try (var stream = index.getRids(session, new CompositeKey("1"))) {
        assertEquals(1, stream.count());
      }
    }
    {
      session.begin();
      var doc = ((EntityImpl) session.newEntity(classD));
      assertEquals("default name", doc.getProperty("name"));
      doc.setProperty("value", "2");

      session.commit();

      try (var stream = index.getRids(session, new CompositeKey("2"))) {
        assertEquals(1, stream.count());
      }
    }
    try (var stream = index.getRids(session, new CompositeKey("3"))) {
      assertEquals(0, stream.count());
    }
  }
}
