/* Generated By:JavaCC: Do not edit this line. YouTrackDBSqlTreeConstants.java Version 7.0.13 */
package com.jetbrains.youtrack.db.internal.core.sql.parser;

public interface YouTrackDBSqlTreeConstants
{
  public int JJTRID = 0;
  public int JJTPARSE = 1;
  public int JJTPARSESCRIPT = 2;
  public int JJTPARSESERVERSTATEMENT = 3;
  public int JJTSTRING = 4;
  public int JJTIDENTIFIER = 5;
  public int JJTINTEGER = 6;
  public int JJTFLOATINGPOINT = 7;
  public int JJTNUMBER = 8;
  public int JJTSERVERSTATEMENT = 9;
  public int JJTSTATEMENT = 10;
  public int JJTSTATEMENTSEMICOLON = 11;
  public int JJTSTATEMENTINTERNAL = 12;
  public int JJTEXPRESSIONSTATEMENT = 13;
  public int JJTQUERYSTATEMENT = 14;
  public int JJTSELECTWITHOUTTARGETSTATEMENT = 15;
  public int JJTSELECTSTATEMENT = 16;
  public int JJTTRAVERSESTATEMENT = 17;
  public int JJTMATCHSTATEMENT = 18;
  public int JJTDELETESTATEMENT = 19;
  public int JJTDELETEVERTEXSTATEMENT = 20;
  public int JJTDELETEEDGESTATEMENT = 21;
  public int JJTDELETEEDGEBYRIDSTATEMENT = 22;
  public int JJTDELETEEDGEFROMTOSTATEMENT = 23;
  public int JJTDELETEEDGETOSTATEMENT = 24;
  public int JJTDELETEEDGEVTOSTATEMENT = 25;
  public int JJTDELETEEDGEWHERESTATEMENT = 26;
  public int JJTUPDATEEDGESTATEMENT = 27;
  public int JJTUPDATESTATEMENT = 28;
  public int JJTUPDATEOPERATIONS = 29;
  public int JJTUPDATEITEM = 30;
  public int JJTUPDATEINCREMENTITEM = 31;
  public int JJTUPDATEREMOVEITEM = 32;
  public int JJTUPDATEPUTITEM = 33;
  public int JJTINSERTSTATEMENT = 34;
  public int JJTINSERTBODY = 35;
  public int JJTCREATEVERTEXSTATEMENTEMPTYNOTARGET = 36;
  public int JJTCREATEVERTEXSTATEMENT = 37;
  public int JJTCREATEVERTEXSTATEMENTNOTARGET = 38;
  public int JJTCREATEEDGESTATEMENT = 39;
  public int JJTINPUTPARAMETER = 40;
  public int JJTPOSITIONALPARAMETER = 41;
  public int JJTNAMEDPARAMETER = 42;
  public int JJTPROJECTION = 43;
  public int JJTPROJECTIONITEM = 44;
  public int JJTNESTEDPROJECTION = 45;
  public int JJTNESTEDPROJECTIONITEM = 46;
  public int JJTARRAYSELECTOR = 47;
  public int JJTARRAYNUMBERSELECTOR = 48;
  public int JJTARRAYSINGLEVALUESSELECTOR = 49;
  public int JJTARRAYRANGESELECTOR = 50;
  public int JJTALIAS = 51;
  public int JJTRECORDATTRIBUTE = 52;
  public int JJTFUNCTIONCALL = 53;
  public int JJTMETHODCALL = 54;
  public int JJTLEVELZEROIDENTIFIER = 55;
  public int JJTSUFFIXIDENTIFIER = 56;
  public int JJTBASEIDENTIFIER = 57;
  public int JJTMODIFIER = 58;
  public int JJTEXPRESSION = 59;
  public int JJTARRAYCONCATEXPRESSION = 60;
  public int JJTARRAYCONCATEXPRESSIONELEMENT = 61;
  public int JJTMATHEXPRESSION = 62;
  public int JJTFIRSTLEVELEXPRESSION = 63;
  public int JJTPARENTHESISEXPRESSION = 64;
  public int JJTBASEEXPRESSION = 65;
  public int JJTFROMCLAUSE = 66;
  public int JJTLETCLAUSE = 67;
  public int JJTLETITEM = 68;
  public int JJTFROMITEM = 69;
  public int JJTMETADATAIDENTIFIER = 70;
  public int JJTINDEXNAME = 71;
  public int JJTWHERECLAUSE = 72;
  public int JJTORBLOCK = 73;
  public int JJTANDBLOCK = 74;
  public int JJTNOTBLOCK = 75;
  public int JJTPARENTHESISBLOCK = 76;
  public int JJTCONDITIONBLOCK = 77;
  public int JJTCOMPAREOPERATOR = 78;
  public int JJTLTOPERATOR = 79;
  public int JJTGTOPERATOR = 80;
  public int JJTNEOPERATOR = 81;
  public int JJTNEQOPERATOR = 82;
  public int JJTGEOPERATOR = 83;
  public int JJTLEOPERATOR = 84;
  public int JJTLIKEOPERATOR = 85;
  public int JJTLUCENEOPERATOR = 86;
  public int JJTNEAROPERATOR = 87;
  public int JJTWITHINOPERATOR = 88;
  public int JJTSCANDOPERATOR = 89;
  public int JJTCONTAINSKEYOPERATOR = 90;
  public int JJTCONTAINSVALUEOPERATOR = 91;
  public int JJTEQUALSCOMPAREOPERATOR = 92;
  public int JJTRIGHTBINARYCONDITION = 93;
  public int JJTBINARYCONDITION = 94;
  public int JJTCONTAINSVALUECONDITION = 95;
  public int JJTINSTANCEOFCONDITION = 96;
  public int JJTBETWEENCONDITION = 97;
  public int JJTISNULLCONDITION = 98;
  public int JJTISNOTNULLCONDITION = 99;
  public int JJTISDEFINEDCONDITION = 100;
  public int JJTISNOTDEFINEDCONDITION = 101;
  public int JJTCONTAINSCONDITION = 102;
  public int JJTINOPERATOR = 103;
  public int JJTINCONDITION = 104;
  public int JJTNOTINCONDITION = 105;
  public int JJTCONTAINSALLCONDITION = 106;
  public int JJTCONTAINSANYCONDITION = 107;
  public int JJTCONTAINSTEXTCONDITION = 108;
  public int JJTMATCHESCONDITION = 109;
  public int JJTORDERBY = 110;
  public int JJTGROUPBY = 111;
  public int JJTUNWIND = 112;
  public int JJTLIMIT = 113;
  public int JJTSKIP = 114;
  public int JJTBATCH = 115;
  public int JJTTIMEOUT = 116;
  public int JJTWAIT = 117;
  public int JJTRETRY = 118;
  public int JJTCOLLECTION = 119;
  public int JJTFETCHPLAN = 120;
  public int JJTFETCHPLANITEM = 121;
  public int JJTTRAVERSEPROJECTIONITEM = 122;
  public int JJTJSON = 123;
  public int JJTMATCHEXPRESSION = 124;
  public int JJTMATCHPATHITEM = 125;
  public int JJTFIELDMATCHPATHITEM = 126;
  public int JJTMATCHPATHITEMFIRST = 127;
  public int JJTMULTIMATCHPATHITEM = 128;
  public int JJTMULTIMATCHPATHITEMARROWS = 129;
  public int JJTMATCHFILTER = 130;
  public int JJTMATCHFILTERITEM = 131;
  public int JJTOUTPATHITEM = 132;
  public int JJTINPATHITEM = 133;
  public int JJTBOTHPATHITEM = 134;
  public int JJTOUTPATHITEMOPT = 135;
  public int JJTINPATHITEMOPT = 136;
  public int JJTBOTHPATHITEMOPT = 137;
  public int JJTPROFILESTORAGESTATEMENT = 138;
  public int JJTTRUNCATECLASSSTATEMENT = 139;
  public int JJTFINDREFERENCESSTATEMENT = 140;
  public int JJTCREATECLASSSTATEMENT = 141;
  public int JJTALTERCLASSSTATEMENT = 142;
  public int JJTDROPCLASSSTATEMENT = 143;
  public int JJTIFNOTEXISTS = 144;
  public int JJTCREATEPROPERTYSTATEMENT = 145;
  public int JJTCREATEPROPERTYATTRIBUTESTATEMENT = 146;
  public int JJTALTERPROPERTYSTATEMENT = 147;
  public int JJTDROPPROPERTYSTATEMENT = 148;
  public int JJTCREATEINDEXSTATEMENT = 149;
  public int JJTREBUILDINDEXSTATEMENT = 150;
  public int JJTDROPINDEXSTATEMENT = 151;
  public int JJTALTERDATABASESTATEMENT = 152;
  public int JJTCOMMANDLINEOPTION = 153;
  public int JJTOPTIMIZEDATABASESTATEMENT = 154;
  public int JJTCREATELINKSTATEMENT = 155;
  public int JJTEXPLAINSTATEMENT = 156;
  public int JJTPROFILESTATEMENT = 157;
  public int JJTPERMISSION = 158;
  public int JJTGRANTSTATEMENT = 159;
  public int JJTREVOKESTATEMENT = 160;
  public int JJTCREATEFUNCTIONSTATEMENT = 161;
  public int JJTCREATESYSTEMUSERSTATEMENT = 162;
  public int JJTEXISTSSYSTEMUSERSTATEMENT = 163;
  public int JJTCREATEUSERSTATEMENT = 164;
  public int JJTDROPUSERSTATEMENT = 165;
  public int JJTALTERROLESTATEMENT = 166;
  public int JJTALTERSYSTEMROLESTATEMENT = 167;
  public int JJTLETSTATEMENT = 168;
  public int JJTBEGINSTATEMENT = 169;
  public int JJTCOMMITSTATEMENT = 170;
  public int JJTROLLBACKSTATEMENT = 171;
  public int JJTRETURNSTATEMENT = 172;
  public int JJTIFSTATEMENT = 173;
  public int JJTSLEEPSTATEMENT = 174;
  public int JJTCONSOLESTATEMENT = 175;
  public int JJTCREATESEQUENCESTATEMENT = 176;
  public int JJTALTERSEQUENCESTATEMENT = 177;
  public int JJTDROPSEQUENCESTATEMENT = 178;
  public int JJTFOREACHBLOCK = 179;
  public int JJTWHILEBLOCK = 180;
  public int JJTSECURITYRESOURCESEGMENT = 181;
  public int JJTCREATESECURITYPOLICYSTATEMENT = 182;
  public int JJTALTERSECURITYPOLICYSTATEMENT = 183;
  public int JJTDATABASEUSERDATA = 184;
  public int JJTCREATEDATABASESTATEMENT = 185;
  public int JJTDROPDATABASESTATEMENT = 186;


  public String[] jjtNodeName = {
    "Rid",
    "parse",
    "parseScript",
    "parseServerStatement",
    "String",
    "Identifier",
    "Integer",
    "FloatingPoint",
    "Number",
    "ServerStatement",
    "Statement",
    "StatementSemicolon",
    "StatementInternal",
    "ExpressionStatement",
    "QueryStatement",
    "SelectWithoutTargetStatement",
    "SelectStatement",
    "TraverseStatement",
    "MatchStatement",
    "DeleteStatement",
    "DeleteVertexStatement",
    "DeleteEdgeStatement",
    "DeleteEdgeByRidStatement",
    "DeleteEdgeFromToStatement",
    "DeleteEdgeToStatement",
    "DeleteEdgeVToStatement",
    "DeleteEdgeWhereStatement",
    "UpdateEdgeStatement",
    "UpdateStatement",
    "UpdateOperations",
    "UpdateItem",
    "UpdateIncrementItem",
    "UpdateRemoveItem",
    "UpdatePutItem",
    "InsertStatement",
    "InsertBody",
    "CreateVertexStatementEmptyNoTarget",
    "CreateVertexStatement",
    "CreateVertexStatementNoTarget",
    "CreateEdgeStatement",
    "InputParameter",
    "PositionalParameter",
    "NamedParameter",
    "Projection",
    "ProjectionItem",
    "NestedProjection",
    "NestedProjectionItem",
    "ArraySelector",
    "ArrayNumberSelector",
    "ArraySingleValuesSelector",
    "ArrayRangeSelector",
    "Alias",
    "RecordAttribute",
    "FunctionCall",
    "MethodCall",
    "LevelZeroIdentifier",
    "SuffixIdentifier",
    "BaseIdentifier",
    "Modifier",
    "Expression",
    "ArrayConcatExpression",
    "ArrayConcatExpressionElement",
    "MathExpression",
    "FirstLevelExpression",
    "ParenthesisExpression",
    "BaseExpression",
    "FromClause",
    "LetClause",
    "LetItem",
    "FromItem",
    "MetadataIdentifier",
    "IndexName",
    "WhereClause",
    "OrBlock",
    "AndBlock",
    "NotBlock",
    "ParenthesisBlock",
    "ConditionBlock",
    "CompareOperator",
    "LtOperator",
    "GtOperator",
    "NeOperator",
    "NeqOperator",
    "GeOperator",
    "LeOperator",
    "LikeOperator",
    "LuceneOperator",
    "NearOperator",
    "WithinOperator",
    "ScAndOperator",
    "ContainsKeyOperator",
    "ContainsValueOperator",
    "EqualsCompareOperator",
    "RightBinaryCondition",
    "BinaryCondition",
    "ContainsValueCondition",
    "InstanceofCondition",
    "BetweenCondition",
    "IsNullCondition",
    "IsNotNullCondition",
    "IsDefinedCondition",
    "IsNotDefinedCondition",
    "ContainsCondition",
    "InOperator",
    "InCondition",
    "NotInCondition",
    "ContainsAllCondition",
    "ContainsAnyCondition",
    "ContainsTextCondition",
    "MatchesCondition",
    "OrderBy",
    "GroupBy",
    "Unwind",
    "Limit",
    "Skip",
    "Batch",
    "Timeout",
    "Wait",
    "Retry",
    "Collection",
    "FetchPlan",
    "FetchPlanItem",
    "TraverseProjectionItem",
    "Json",
    "MatchExpression",
    "MatchPathItem",
    "FieldMatchPathItem",
    "MatchPathItemFirst",
    "MultiMatchPathItem",
    "MultiMatchPathItemArrows",
    "MatchFilter",
    "MatchFilterItem",
    "OutPathItem",
    "InPathItem",
    "BothPathItem",
    "OutPathItemOpt",
    "InPathItemOpt",
    "BothPathItemOpt",
    "ProfileStorageStatement",
    "TruncateClassStatement",
    "FindReferencesStatement",
    "CreateClassStatement",
    "AlterClassStatement",
    "DropClassStatement",
    "IfNotExists",
    "CreatePropertyStatement",
    "CreatePropertyAttributeStatement",
    "AlterPropertyStatement",
    "DropPropertyStatement",
    "CreateIndexStatement",
    "RebuildIndexStatement",
    "DropIndexStatement",
    "AlterDatabaseStatement",
    "CommandLineOption",
    "OptimizeDatabaseStatement",
    "CreateLinkStatement",
    "ExplainStatement",
    "ProfileStatement",
    "Permission",
    "GrantStatement",
    "RevokeStatement",
    "CreateFunctionStatement",
    "CreateSystemUserStatement",
    "ExistsSystemUserStatement",
    "CreateUserStatement",
    "DropUserStatement",
    "AlterRoleStatement",
    "AlterSystemRoleStatement",
    "LetStatement",
    "BeginStatement",
    "CommitStatement",
    "RollbackStatement",
    "ReturnStatement",
    "IfStatement",
    "SleepStatement",
    "ConsoleStatement",
    "CreateSequenceStatement",
    "AlterSequenceStatement",
    "DropSequenceStatement",
    "ForEachBlock",
    "WhileBlock",
    "SecurityResourceSegment",
    "CreateSecurityPolicyStatement",
    "AlterSecurityPolicyStatement",
    "DatabaseUserData",
    "CreateDatabaseStatement",
    "DropDatabaseStatement",
  };
}
/* JavaCC - OriginalChecksum=b39cd7909e97795412fa73cb63f79cf1 (do not edit this line) */
