/* Generated By:JavaCC: Do not edit this line. YouTrackDBSqlVisitor.java Version 7.0.13 */
package com.jetbrains.youtrack.db.internal.core.sql.parser;

public interface YouTrackDBSqlVisitor {

  Object visit(SimpleNode node, Object data);

  Object visit(SQLRid node, Object data);

  Object visit(SQLparse node, Object data);

  Object visit(SQLparseScript node, Object data);

  Object visit(SQLparseServerStatement node, Object data);

  Object visit(SQLString node, Object data);

  Object visit(SQLIdentifier node, Object data);

  Object visit(SQLInteger node, Object data);

  Object visit(SQLFloatingPoint node, Object data);

  Object visit(SQLNumber node, Object data);

  Object visit(SQLServerStatement node, Object data);

  Object visit(SQLStatement node, Object data);

  Object visit(SQLStatementSemicolon node, Object data);

  Object visit(SQLStatementInternal node, Object data);

  Object visit(SQLExpressionStatement node, Object data);

  Object visit(SQLQueryStatement node, Object data);

  Object visit(SQLSelectWithoutTargetStatement node, Object data);

  Object visit(SQLSelectStatement node, Object data);

  Object visit(SQLTraverseStatement node, Object data);

  Object visit(SQLMatchStatement node, Object data);

  Object visit(SQLDeleteStatement node, Object data);

  Object visit(SQLDeleteVertexStatement node, Object data);

  Object visit(SQLDeleteEdgeStatement node, Object data);

  Object visit(SQLDeleteEdgeByRidStatement node, Object data);

  Object visit(SQLDeleteEdgeFromToStatement node, Object data);

  Object visit(SQLDeleteEdgeToStatement node, Object data);

  Object visit(SQLDeleteEdgeVToStatement node, Object data);

  Object visit(SQLDeleteEdgeWhereStatement node, Object data);

  Object visit(SQLUpdateEdgeStatement node, Object data);

  Object visit(SQLUpdateStatement node, Object data);

  Object visit(SQLUpdateOperations node, Object data);

  Object visit(SQLUpdateItem node, Object data);

  Object visit(SQLUpdateIncrementItem node, Object data);

  Object visit(SQLUpdateRemoveItem node, Object data);

  Object visit(SQLUpdatePutItem node, Object data);

  Object visit(SQLInsertStatement node, Object data);

  Object visit(SQLInsertBody node, Object data);

  Object visit(SQLCreateVertexStatementEmptyNoTarget node, Object data);

  Object visit(SQLCreateVertexStatement node, Object data);

  Object visit(SQLCreateVertexStatementNoTarget node, Object data);

  Object visit(SQLMoveVertexStatement node, Object data);

  Object visit(SQLCreateEdgeStatement node, Object data);

  Object visit(SQLInputParameter node, Object data);

  Object visit(SQLPositionalParameter node, Object data);

  Object visit(SQLNamedParameter node, Object data);

  Object visit(SQLProjection node, Object data);

  Object visit(SQLProjectionItem node, Object data);

  Object visit(SQLNestedProjection node, Object data);

  Object visit(SQLNestedProjectionItem node, Object data);

  Object visit(SQLArraySelector node, Object data);

  Object visit(SQLArrayNumberSelector node, Object data);

  Object visit(SQLArraySingleValuesSelector node, Object data);

  Object visit(SQLArrayRangeSelector node, Object data);

  Object visit(SQLAlias node, Object data);

  Object visit(SQLRecordAttribute node, Object data);

  Object visit(SQLFunctionCall node, Object data);

  Object visit(SQLMethodCall node, Object data);

  Object visit(SQLLevelZeroIdentifier node, Object data);

  Object visit(SQLSuffixIdentifier node, Object data);

  Object visit(SQLBaseIdentifier node, Object data);

  Object visit(SQLModifier node, Object data);

  Object visit(SQLExpression node, Object data);

  Object visit(SQLArrayConcatExpression node, Object data);

  Object visit(SQLArrayConcatExpressionElement node, Object data);

  Object visit(SQLMathExpression node, Object data);

  Object visit(SQLFirstLevelExpression node, Object data);

  Object visit(SQLParenthesisExpression node, Object data);

  Object visit(SQLBaseExpression node, Object data);

  Object visit(SQLFromClause node, Object data);

  Object visit(SQLLetClause node, Object data);

  Object visit(SQLLetItem node, Object data);

  Object visit(SQLFromItem node, Object data);

  Object visit(SQLCluster node, Object data);

  Object visit(SQLClusterList node, Object data);

  Object visit(SQLMetadataIdentifier node, Object data);

  Object visit(SQLIndexName node, Object data);

  Object visit(SQLIndexIdentifier node, Object data);

  Object visit(SQLWhereClause node, Object data);

  Object visit(SQLOrBlock node, Object data);

  Object visit(SQLAndBlock node, Object data);

  Object visit(SQLNotBlock node, Object data);

  Object visit(SQLParenthesisBlock node, Object data);

  Object visit(SQLConditionBlock node, Object data);

  Object visit(SQLCompareOperator node, Object data);

  Object visit(SQLLtOperator node, Object data);

  Object visit(SQLGtOperator node, Object data);

  Object visit(SQLNeOperator node, Object data);

  Object visit(SQLNeqOperator node, Object data);

  Object visit(SQLGeOperator node, Object data);

  Object visit(SQLLeOperator node, Object data);

  Object visit(SQLLikeOperator node, Object data);

  Object visit(SQLLuceneOperator node, Object data);

  Object visit(SQLNearOperator node, Object data);

  Object visit(SQLWithinOperator node, Object data);

  Object visit(SQLScAndOperator node, Object data);

  Object visit(SQLContainsKeyOperator node, Object data);

  Object visit(SQLContainsValueOperator node, Object data);

  Object visit(SQLEqualsCompareOperator node, Object data);

  Object visit(SQLRightBinaryCondition node, Object data);

  Object visit(SQLBinaryCondition node, Object data);

  Object visit(SQLContainsValueCondition node, Object data);

  Object visit(SQLInstanceofCondition node, Object data);

  Object visit(SQLBetweenCondition node, Object data);

  Object visit(SQLIsNullCondition node, Object data);

  Object visit(SQLIsNotNullCondition node, Object data);

  Object visit(SQLIsDefinedCondition node, Object data);

  Object visit(SQLIsNotDefinedCondition node, Object data);

  Object visit(SQLContainsCondition node, Object data);

  Object visit(SQLInOperator node, Object data);

  Object visit(SQLInCondition node, Object data);

  Object visit(SQLNotInCondition node, Object data);

  Object visit(SQLContainsAllCondition node, Object data);

  Object visit(SQLContainsAnyCondition node, Object data);

  Object visit(SQLContainsTextCondition node, Object data);

  Object visit(SQLMatchesCondition node, Object data);

  Object visit(SQLOrderBy node, Object data);

  Object visit(SQLGroupBy node, Object data);

  Object visit(SQLUnwind node, Object data);

  Object visit(SQLLimit node, Object data);

  Object visit(SQLSkip node, Object data);

  Object visit(SQLBatch node, Object data);

  Object visit(SQLTimeout node, Object data);

  Object visit(SQLWait node, Object data);

  Object visit(SQLRetry node, Object data);

  Object visit(SQLCollection node, Object data);

  Object visit(SQLFetchPlan node, Object data);

  Object visit(SQLFetchPlanItem node, Object data);

  Object visit(SQLTraverseProjectionItem node, Object data);

  Object visit(SQLJson node, Object data);

  Object visit(SQLMatchExpression node, Object data);

  Object visit(SQLMatchPathItem node, Object data);

  Object visit(SQLFieldMatchPathItem node, Object data);

  Object visit(SQLMatchPathItemFirst node, Object data);

  Object visit(SQLMultiMatchPathItem node, Object data);

  Object visit(SQLMultiMatchPathItemArrows node, Object data);

  Object visit(SQLMatchFilter node, Object data);

  Object visit(SQLMatchFilterItem node, Object data);

  Object visit(SQLOutPathItem node, Object data);

  Object visit(SQLInPathItem node, Object data);

  Object visit(SQLBothPathItem node, Object data);

  Object visit(SQLOutPathItemOpt node, Object data);

  Object visit(SQLInPathItemOpt node, Object data);

  Object visit(SQLBothPathItemOpt node, Object data);

  Object visit(SQLProfileStorageStatement node, Object data);

  Object visit(SQLTruncateClassStatement node, Object data);

  Object visit(SQLFindReferencesStatement node, Object data);

  Object visit(SQLCreateClassStatement node, Object data);

  Object visit(SQLAlterClassStatement node, Object data);

  Object visit(SQLDropClassStatement node, Object data);

  Object visit(SQLIfNotExists node, Object data);

  Object visit(SQLCreatePropertyStatement node, Object data);

  Object visit(SQLCreatePropertyAttributeStatement node, Object data);

  Object visit(SQLAlterPropertyStatement node, Object data);

  Object visit(SQLDropPropertyStatement node, Object data);

  Object visit(SQLCreateIndexStatement node, Object data);

  Object visit(SQLRebuildIndexStatement node, Object data);

  Object visit(SQLDropIndexStatement node, Object data);

  Object visit(SQLCreateClusterStatement node, Object data);

  Object visit(SQLAlterClusterStatement node, Object data);

  Object visit(SQLAlterDatabaseStatement node, Object data);

  Object visit(SQLCommandLineOption node, Object data);

  Object visit(SQLOptimizeDatabaseStatement node, Object data);

  Object visit(SQLCreateLinkStatement node, Object data);

  Object visit(SQLExplainStatement node, Object data);

  Object visit(SQLProfileStatement node, Object data);

  Object visit(SQLPermission node, Object data);

  Object visit(SQLGrantStatement node, Object data);

  Object visit(SQLRevokeStatement node, Object data);

  Object visit(SQLCreateFunctionStatement node, Object data);

  Object visit(SQLCreateSystemUserStatement node, Object data);

  Object visit(SQLExistsSystemUserStatement node, Object data);

  Object visit(SQLCreateUserStatement node, Object data);

  Object visit(SQLDropUserStatement node, Object data);

  Object visit(SQLAlterRoleStatement node, Object data);

  Object visit(SQLAlterSystemRoleStatement node, Object data);

  Object visit(SQLLetStatement node, Object data);

  Object visit(SQLBeginStatement node, Object data);

  Object visit(SQLCommitStatement node, Object data);

  Object visit(SQLRollbackStatement node, Object data);

  Object visit(SQLReturnStatement node, Object data);

  Object visit(SQLIfStatement node, Object data);

  Object visit(SQLSleepStatement node, Object data);

  Object visit(SQLConsoleStatement node, Object data);

  Object visit(SQLCreateSequenceStatement node, Object data);

  Object visit(SQLAlterSequenceStatement node, Object data);

  Object visit(SQLDropSequenceStatement node, Object data);

  Object visit(SQLForEachBlock node, Object data);

  Object visit(SQLWhileBlock node, Object data);

  Object visit(SQLSecurityResourceSegment node, Object data);

  Object visit(SQLCreateSecurityPolicyStatement node, Object data);

  Object visit(SQLAlterSecurityPolicyStatement node, Object data);

  Object visit(SQLDatabaseUserData node, Object data);

  Object visit(SQLCreateDatabaseStatement node, Object data);

  Object visit(SQLDropDatabaseStatement node, Object data);
}
/* JavaCC - OriginalChecksum=2943ca18a09e7db0d96d2590c99cb7af (do not edit this line) */
